### ISSUE TITLE
Compact Ores unminable.

### ISSUE THREAD

**Issue by Jcewazhere** [Direwolf20-MC/MiningGadgets#100]
The ores from compact ores can't be mined with the gadget. 
If you've never seen that mod it creates extensions of ores from vanilla and other mods that drop several of the ore at once when mined.

**Comment by MichaelHillcox** [comment]
What do you mean by can't? It's entirely possible that they are tile entities which would be awful but still.

**Comment by Jcewazhere** [comment]
I mean that in 3X3 mode holding right click will mine everything around the compact ores, but not that ore itself. Nor will using 1X1 mode. 

My java is really rusty, but if I'm reading https://github.com/DoubleNegation/CompactOres/blob/1.15/src/main/java/doublenegation/mods/compactores/CompactOreBlock.java right they might actually be tile entities. It's weird that having that many tile entities around doesn't cause a bit of lag. Maybe because they're not ticking? IDK.

The mining gadget and 'Low-tech quarries' are the only two mods I've ever seen have problems with these ores. Hammers, tinkers construct, silent gems, buildcraft quarries, etc have never had issues with them.

Does the mining gadget work by creating a copy of the ore or does it break the blocks like vanilla tools would? 

![2020-06-20_16 20 59](https://user-images.githubusercontent.com/6025499/85212671-45336200-b312-11ea-9e08-8d22ea0d8039.png)

![2020-06-20_16 21 04](https://user-images.githubusercontent.com/6025499/85212676-50868d80-b312-11ea-9891-9cc4ded2e1e2.png)

![2020-06-20_16 21 04_2](https://user-images.githubusercontent.com/6025499/85212677-541a1480-b312-11ea-8434-c24eb0af4018.png)

**Comment by Direwolf20-MC** [comment]
That definitely would be the cause. I have tile entities blacklisted mostly for safety. Sorry :( doubt there’s anything I can do.

**Comment by Jcewazhere** [comment]
Okay, thanks for responding :D
