### ISSUE TITLE
Loading the game fails when sneak is bound to a mouse button or unbound

### ISSUE THREAD

**Issue by winauer** [Direwolf20-MC/MiningGadgets#101]
When sneak is bound to a mouse button a window saying 

> GLFW error 65539: Invalid key 0.

> Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

pops up and the game window freezes/loading the game stops.

The number of the invalid key changes depending on the mouse key that is bound to sneak. When sneak is unbound the number is -1.

Screenshot of error window: https://i.imgur.com/HmcGbCK.png

MultiMC log after clicking OK on that window: https://paste.ee/p/bkvQP

**Comment by MichaelHillcox** [comment]
I hate to say this but, update your drivers, I know you're on linux but this seems to be an issue with MC and not this mod as we've had this issue pop up everywhere. What version are you on? Sorry for the stupidly late reply @winauer

**Comment by winauer** [comment]
No, it's definitely a mod issue. It still happens on 1.16.4. I think the problem is this line:

https://github.com/Direwolf20-MC/MiningGadgets/blob/master/src/main/java/com/direwolf20/mininggadgets/common/items/MiningGadget.java#L115

Changing that to just `boolean sneakPressed = false;` gets rid of the crash, but it also gets rid of the intended behavior. Unfortunately I don't know enough about modding yet to know how to fix it properly. Mekanism had a similar issue. Please take a look on how they fixed it here:

https://github.com/mekanism/Mekanism/commit/ebf079c3f00774a06582e98f0fb41bd49a294d48#diff-6e1f3f1db028f612b7a9c0884904c777d7a3fb898e38270148013bd276c5b8a9R41

**Comment by MichaelHillcox** [comment]
They're just wrapping the crash, not solving it, the reason I say it's an MC thing as all of us modding the game run into this issue every now and then, Thanks for the links though, I'll see if I can wrap the crash to fix it for you. Can you think of any MC in-game things that require shift to be held that aren't handled on the server?

**Comment by winauer** [comment]
> They're just wrapping the crash, not solving it, the reason I say it's an MC thing as all of us modding the game run into this issue every now and then

Ah, thanks for the info

> Can you think of any MC in-game things that require shift to be held that aren't handled on the server?

No idea, sorry.

Thanks for looking into it.

**Comment by MichaelHillcox** [comment]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177
