### ISSUE TITLE
Fortune Addon

### ISSUE THREAD

**Issue by keremlov** [Direwolf20-MC/MiningGadgets#102]
I am playing this on the enigmatica 6 modpack and fortune addons do not work.

**Comment by MichaelHillcox** [comment]
They should... hmm, what version are you on?

**Comment by keremlov** [comment]
1.16.1

**Comment by MichaelHillcox** [comment]
Thanks, what level of fortune did you have?

**Comment by keremlov** [comment]
Fortune 3, I tried on coal, diamond and redstone. I just get the same amount as if it's a normal pickaxe

**Comment by MichaelHillcox** [comment]
Alrighty, maybe something has changed, I'll take a peak

**Comment by keremlov** [comment]
Hello again, I restarted the client and it worked. Sorry for the long wait, couldn't get the pc.

**Comment by jinkhya** [comment]
Hello, I'm also experiencing this on Enigmatica 6. That being said it's only the Fortune III that is not working for me. For testing purposes I mined 24 diamonds with each Fortune level and only fortune III was returning 1 diamond on every single ore. (same for quartz and probably other ores).

**Comment by jinkhya** [comment]
I restarted my client and it fixed it like Keremlov. Weird issue. (I wonder if it's related to the the laser beam sometimes not showing and getting fixed with a restart. I had the fortune III issue when I had no laser beam, and now my laser beam is showing properly and so is the fortune III addon).

**Comment by MichaelHillcox** [comment]
Going to close until someone can find a way to reproduce. It might be an issue with other mods.
