### ISSUE TITLE
[1.16.1] [Rendering Bug] Laser beam jumps to new position we sneaking 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [Direwolf20-MC/MiningGadgets#104]
When sneaking while using the mining gadget the laser beam will jump down to the new position and the gadget will glide there meaning that the laser beam will get there first, the same is true when letting go of the sneak button the laser beam will jump up and the gadget will glide up

![2020-08-24_21 25 19](https://user-images.githubusercontent.com/11648771/91092885-90d6f480-e650-11ea-82ff-f25f37b0b01e.png)

![2020-08-24_21 26 42_3](https://user-images.githubusercontent.com/11648771/91092921-9c2a2000-e650-11ea-8773-d3681455c7ba.png)

**Comment by MichaelHillcox** [comment]
Yeah, thanks minecraft! Ugh... This is a painful one to fix. I'll need to consult with some other devs

**Comment by Direwolf20-MC** [comment]
Should be fixed :)
