### ISSUE TITLE
[1.16.1]Add compatibility with Immersive Engineering Charging station

### ISSUE THREAD

**Issue by jinkhya** [Direwolf20-MC/MiningGadgets#105]
Hello !
It'd be cool to be able to charge the gadgets in Immersive Engineering's Charging station. It doesn't have a UI so you have to right click the charger to add/remove items to charge. The trick is currently to use for example a hopper to transfer the gadgets into the charger, which works fine but more of a workaround :) 
Thanks !

**Comment by MichaelHillcox** [comment]
No worries. Transfering it now :+1:

**Comment by jinkhya** [comment]
cheers !

**Comment by MichaelHillcox** [comment]
So yes, I know what you mean and I should be able to see if I can support this 👍

**Comment by jinkhya** [comment]
awesome thank you ! :D

**Comment by MichaelHillcox** [comment]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177
