### ISSUE TITLE
[Suggestion] Beam filter addons and mining helmet

### ISSUE THREAD

**Issue by deriamis** [Direwolf20-MC/MiningGadgets#106]
I was just watching Dire's Forgecraft stream VOD today, and I suddenly had an idea for something that would be useful in the Mining Gadgets - a beam filter addon that causes the beam to *only* mine one or a given set of blocks, or to make it *not* mine one or a given set of blocks. This would make it possible to, for instance, keep your mining beam from breaking your base blocks and machines, which the void upgrade would not help with.

Another similar addon could be used to make all other blocks transparent to the beam, which would let you "reach behind" blocks to get at something else without breaking the blocks between. Finally, a helmet upgrade (possibly also usable as a bauble?) could be used to visualize the blocks the mining gadget would mine, potentially with its own upgrades for finding ores and intervening block transparency.

**Comment by MichaelHillcox** [comment]
First idea is already a thing, checkout the filter upgrade 👍 
Second idea is also mostly a thing, we've disabled showing what blocks it won't mine so it only shows it's AOF atm but we plan to add it back sometime soon. Gunna go ahead and close this but feel free to keep the conversation going
