### ISSUE TITLE
Crash "GLFW error 65539: invalid key3." because of keybind

### ISSUE THREAD

**Issue by lieven121** [Direwolf20-MC/MiningGadgets#108]
Took me a while to find out why I couldn't play with mining gadgets. 
Found it now.
When sneak is set to mouse button 4 it causes a GLFW error the next time it starts.
![image](https://user-images.githubusercontent.com/7773244/92331185-10af8680-f075-11ea-96af-985cc1cbfc92.png)

Sadly enough I can't find any reason why this is causing this crash.
This was tested in version
minecraft: 1.16.1
forge: 32.0.108
mining gadgets: 1.4.1

But I have had this problem as far back as I can remember.

**Comment by lieven121** [comment]
with a closer look, it might have something to do with the tooltip 
![image](https://user-images.githubusercontent.com/7773244/92334000-36935600-f08a-11ea-8985-a673d065e23a.png) (not sure tough)

**Comment by MaxNeedsSnacks** [comment]
I've been made aware that this is apparently a *vanilla* issue fixed in MC 1.16.2, as my friend had a similar problem. Does it happen with any other mods other than Mining Gadgets?

**Comment by lieven121** [comment]
I launched all the mods 6 and didn't have any problem (if I disabled mining gadgets) so I would say probably no.

**Comment by MichaelHillcox** [comment]
Still trying to figure out this issue but that's for the report

**Comment by MichaelHillcox** [comment]
Can you let me know if this still happens in 1.16.4? I can't produce this issue with my system or hardware

**Comment by MichaelHillcox** [comment]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177

**Comment by Majorwoops** [comment]
![Minecraft__1 18 2_5_4_2023_9_51_26_AM](https://user-images.githubusercontent.com/132602990/236278587-356ebc8b-bb49-4e19-a2d3-f77486b2cbf7.png)

i saw that it was solved in mining gadgets version 1.7.1 

i am trying to play vault hunters and it has mining gadgets version 1.11.1 im wondering if it was kinda resurfaced in this version
