### ISSUE TITLE
[1.16.1] Rendering issues with EngineersDecor and (another mod I haven't been able to pin down)

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [Direwolf20-MC/MiningGadgets#109]
Hey o/

I've been playing `Enigmatica 6` (version `0.2.16`) recently and I've actually gotten quite frustrated at the fact that *any* sort of visual feedback from MiningGadgets seems to stop functioning seemingly at random between pack restarts (I've consistently been able to reproduce the mining beam not working, while others indicate a pack restart fixed any issues for them, at least temporarily).

After **a lot** of testing I've determined that the rendering system seems to be breaking whenever EngineersDecor ***and*** one specific other mod are installed at the same time (which mod that is, I haven't been able to determine just yet as launching the testing instance over and over again takes time), which means that both the laser beam rendering as well as block break particles and even the little green overlay for AOE modes just stop rendering altogether. I've already checked both the regular and debug logs for any errors out of the ordinary, however nothing seems to indicate anything fishy unfortunately.

If you're able to find the cause of this issue, that'd be absolutely amazing, I've honestly been feeling like I was going mad after trying to find the culprits for this ^^

(Forge is on version `32.0.108`, with Mining Gadgets `1.4.1`)

**Comment by MaxNeedsSnacks** [comment]
A quick note: This **may** be similar to #88, though I haven't found the stray laser (if it renders at all) so this *might* also be something entirely different

**Comment by MichaelHillcox** [comment]
Hmm, that's really odd as I play with the mod on 1.16 ForgeCraft and don't have an issue and I know that EngineersDecor is in the pack so it might be a conflict between that mod and another mod causing a render leak.

**Comment by brckts** [comment]
Sometimes just relaunching the game without changing anything fixes it.

**Comment by MichaelHillcox** [comment]
Yeah, that seems very weird. Does it happen in a fresh world when only having given yourself a Mining Gadget?

**Comment by brckts** [comment]
> Yeah, that seems very weird. Does it happen in a fresh world when only having given yourself a Mining Gadget?

Testing methodology was:
Start a fresh world
Give myself a mining gadget, solar generator and energy cube
Mine with it

**Comment by MichaelHillcox** [comment]
Did it still happen?

**Comment by brckts** [comment]
Sometimes yes, sometimes no, that's the weird part

**Comment by MichaelHillcox** [comment]
You'd have to try and narrow down the mods that are causing it so I can see if I can figure out if it's us or them

**Comment by brckts** [comment]
To be more precise, I tried a bunch of things to narrow down when it appeared by reverting back to older versions of the pack and seeing which addition broke it but to no avail. Then I created a fresh instance with 0.2.16 and a fresh world and it worked again. Mind you the initial test was also on a fresh instance on a fresh world and it didn't work

**Comment by MaxNeedsSnacks** [comment]
![image](https://user-images.githubusercontent.com/12750501/92409496-225e6000-f141-11ea-8982-d9d34438c129.png)

This is what my testing instance was whittled down to in the end, I tried removing Mek, but for some reason, this causes Building Gadgets to crash on launch

**Comment by MichaelHillcox** [comment]
Stupid Building Gadgets haha! if you could hand me that crashlog anyway that would be helpful for Building Gadgets but just remove BG if it's causing an issue 👍

**Comment by brckts** [comment]
From my testing, the rendering broke back in 0.2.9, I looked at what was added and try disabling new/updated mod from that update. I narrowed it down to connected glass. 
Disabled it fixed it up to modpack version 0.2.14 where it broke again and I couldn't narrow it down.

But then again, _sometimes_ it works without changing anything, sometimes it doesn't.

**Comment by MaxNeedsSnacks** [comment]
> Stupid Building Gadgets haha! if you could hand me that crashlog anyway that would be helpful for Building Gadgets but just remove BG if it's causing an issue 👍

The crash log's quite generic, but it seems to happen consistently without Mek ^^
[crash-2020-09-07_16.11.30-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/5184305/crash-2020-09-07_16.11.30-client.txt)

I'm currently launching without BG **or** Mek

**Comment by MichaelHillcox** [comment]
That's an extremely weird crash, when does that happen, when trying to load the world?

**Comment by MaxNeedsSnacks** [comment]
Nope, on startup it seems, but it happens consistently enough to the point where I don't think it's a one-off

**Comment by MaxNeedsSnacks** [comment]
Seems ***that*** crash is idadvertently caused by another mod, Laser Relays

```java
[1;31m[19:42:12] [Render thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:block_entity_type> dispatch for modid laserrelays
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: tfar.laserrelays.NodeBlockEntity.<init>()void/newInvokeSpecial
```

**Comment by MaxNeedsSnacks** [comment]
This is a weird glitch I'll probably ignore for now (or forward to the author of Laser Relays later), as for the weird rendering issue, still working on that right now, but it seems Laser Relays is also at least **involved** in that somehow

**Comment by MaxNeedsSnacks** [comment]
Yup, Laser Relays is definitely the culprit for this situation here! \o/
I don't know why this didn't come up in my round of testing, because I just did "binary search" with the mods (split them up into halves) and discovered the issue was in *both* halves for some reason... might've forgotten to actually put Laser Relays into one of the two halves by accident, whoops!

**Comment by MichaelHillcox** [comment]
Awesome!

**Comment by MaxNeedsSnacks** [comment]
The Render Leak in Laser Relays has been fixed! \o/ I'll be testing later tonight whether this has also fixed the issue within the pack, since other than that, I don't think there are any other problems!
