### ISSUE TITLE
Visual or auditory feedback when a block breaks

### ISSUE THREAD

**Issue by nickalbrecht** [Direwolf20-MC/MiningGadgets#110]
Just started using this mod. The one thing that immediately jumps out to me, after using other tools, is that I think it needs some sort of visual or auditory cue when mining a block is finished. I felt it was _sort-of_ related to the "break styles" but not really? Even if the styles are left at just "fade" or "shrink", there should really be some sort of cue that lets you know that mining a block finished before it starts on the next one hit by the laser, or to let you know you can move it over to an adjacent one. Currently, there's very little feedback when mining a block finishes and it starts mining the next one.

Currently using Mining Gadgets v1.3.5 for 1.15.2 as included in the Valhelsia modpack.

**Comment by nickalbrecht** [comment]
It arguably becomes less of an issue with a fully upgraded laser since it seems to be more geared towards mass excavating rapid for resource gathering. Precision mode helps, but I feel like even with that, a soft/low volume breaking sound would be nice to have.

**Comment by MichaelHillcox** [comment]
I like this idea, definitely going to make it optional 👍

**Comment by mikent2016** [comment]
I just started using the mod and I agree, the lack of feedback for breaking blocks is a problem for usability and just for the satisfaction of breaking blocks. Has there been any progress on this issue?
