### ISSUE TITLE
[1.15.2] Crash in laser menu when scroll wheeling

### ISSUE THREAD

**Issue by CGarland97** [Direwolf20-MC/MiningGadgets#112]
The lag is almost certainly unrelated to Mining Gadgets (I'm running a slightly underpowered rig), but whilst mining I shift clicked just as a lag spike hit. Like normal (for me) the game froze (which I expected to last a second or 2), just as I opened the laser UI, but instead of unfreezing, Minecraft fully locked up and started closing the world before the entire client crashed.

The crash log suggests that I also scroll wheeled, which is a possibility, although I don't remember doing such. This is probably a very niche crash, but as it is a full crash to desktop, I thought it was worth reporting.

(If I remember tomorrow I'll try and replicate the crash)

Modpack: FTB Omnia
MC Version: 1.15.2
Forge Version: 31.2.31
Crash Log: https://pastebin.com/WMLhyZhM

**Comment by MichaelHillcox** [comment]
Oh, another odd GUI one, intresting, I'll have a look today :+1:

**Comment by CGarland97** [comment]
Did a quick replication test and it seems that the lag played no part in the crash, instead just the act of using the scroll wheel whilst in the laser GUI caused what appears to be the exact same crash (creating the exact same crash log apart from the time)

**Comment by CGarland97** [comment]
Testing with MC 1.16.2, Forge 33.0.42 and the latest version of mining gadgets (I think they're the same? but I wanted to make sure the bug is still present), the crash seems to be related to line 254 of MiningSettingScreen.java, which is the freeze delay slider, which is not installed in the gadget. (Only visible in the game output, not the crash log)

If the freezing upgrade is installed, then scrolling does not crash the game, so I think the error is related to that. 

(Is the freeze delay slider not initiated until the upgrade is installed, thus causing this null pointer exception? Sorry if this is not helpful)

**Comment by MichaelHillcox** [comment]
Fixed will be released shortly
