### ISSUE TITLE
Redstone mining issue

### ISSUE THREAD

**Issue by IamStig** [Direwolf20-MC/MiningGadgets#114]
Mining Gadget version 1.5.1 for 1.16.2
minecraftforge version 33.0.61

When mining redstone if closer than 5-6 blocks the miner will try to hit the block rather than mine. Moving further away solves the problem by if your making a turn and don't have room you have to mine around it and mine the redstone when you have the distance.
Active upgrades are Efficiency T5, Fortune T3, Range T2, Freeze, Magnet and Light.

**Comment by MichaelHillcox** [comment]
Ah, I forgot about redstone, I'll add a check in for that, sorry about that :P

**Comment by MichaelHillcox** [comment]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177

**Comment by IamStig** [comment]
Query ....the 1.7.1 file is labeled 1.16.4, is it only 1.16.4 or should it be usable on 1.16.3 and tag  supported version missed?

**Comment by MichaelHillcox** [comment]
Hmm, You can try it on 1.16.3, but no, I've only targetted the latest version for this fix.

**Comment by IamStig** [comment]
Limited testing but 1.71 seems fine on 1.16.3 and the redstone mining is working fine. Thanks for you hard work Mikey

**Comment by MichaelHillcox** [comment]
Happy to help
