### ISSUE TITLE
[1.16.3] Mining Gadget vanishes when placed in Modification Table fully charged

### ISSUE THREAD

**Issue by lycanthrope7** [Direwolf20-MC/MiningGadgets#115]
Forge Ver: 34.1.0
Mod Ver: 1.6.0
Modpack: My own (59 mods in total)
Environment: Single-Player World

Whenever I place the Mining Gadget into the Modification Table while it's fully charged, it vanishes. If I drain the battery first, even the slightest bit, it works fine.

I use a Player Transmitter from the Powah mod to charge devices while they're in my inventory. It keeps my Building Gadgets and Mining Gadget fully charged at all times. I'm not sure if this is what's causing the issue. I don't have any other way to charge the gadgets at present.

The number and type of modifications installed on the gadget seems to make no difference.

**Comment by MichaelHillcox** [comment]
How strange, ill take a look

**Comment by ViRb3** [comment]
Happened three times to me over the last few days. It only seems to happen if I'm on creative, I think, but I don't have an exact reproduction.

**Comment by MichaelHillcox** [comment]
It's likely a mod conflict but I can look into it

**Comment by MichaelHillcox** [comment]
I can't for the life of my reproduce this. If you can find a way to please let me know so I can get it fixed.

**Comment by MichaelHillcox** [comment]
Oh! JEI was deleting it! I've fixed this #142 hope I'm right! Let me know if it still happens when I release the next update
