### ISSUE TITLE
Add config for adding another tier of efficiency for modded hardness

### ISSUE THREAD

**Issue by Letoric** [Direwolf20-MC/MiningGadgets#116]
When using ATM 1.16.3, in the new dimension "Other" the ores are tier 6, and are showing a "render block don't use" tool tip, and also mining quite slowly. Is there any chance you can add in an upgrade or ability to work through to a higher tier/speed of mining than the gadget is currently set for (it mines it, but slowly as mentioned) and also fix the tool tip issue?

I know this is not completely on you, your mod wasn't expecting their tier 6 stuff, just asking if you can work with it.

Thanks!

**Comment by MichaelHillcox** [comment]
So the render block doesn’t mimic the blocks name as that’s not a super simple task to do, we could do it but for most blocks it’s a pretty quick mine so we’ve found it to be pretty pointless. If you’re actually picking up blocks with this name then that’s a completely different issue...

As for the mining speed, we find that it’s almost instant mine with normal blocks in MC and pretty quick for everything else. I guess I could add a few higher tiers into the mix with a ‘by default disabled’ config option to make the gadget less OP. I’ll ask dire

**Comment by Letoric** [comment]
Thanks for checking. It's definitely NOT quick for the tier 6 stuff by ATM
team. It's about 20 seconds or slower, with a fully upgraded mining gadget.

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
