### ISSUE TITLE
Negative energy value makes gadget unchargeable

### ISSUE THREAD

**Issue by NightOps007** [Direwolf20-MC/MiningGadgets#117]
I hit a little lag spike during an autosave and afterwards my mining laser had used up the last of its energy and even went negative by the time the server caught up. It won't charge anymore with the negative energy value on it.

**Comment by MichaelHillcox** [comment]
What version of MC and the mod

**Comment by NightOps007** [comment]
MC-1.15.2
forge-31.2.45
mininggadgets-1.3.5

**Comment by MichaelHillcox** [comment]
Yeah, I think I fixed this in 1.16, I'll patch it up soon

**Comment by NightOps007** [comment]
Great!
