### ISSUE TITLE
Shift + Rt click isn't opening options

### ISSUE THREAD

**Issue by BigAl607** [Direwolf20-MC/MiningGadgets#118]
I have the 3x3 mod added to the mining gadget, as well as a few others. By default, the laser is set at 1x1. When I shift-click to select the 3x3 option, nothing happens other than the gadget visibly moving in my hand.

version 1.6.0, MC version 1.16.3, custom pack

**Comment by MichaelHillcox** [comment]
Have you got a key binding set for the gadget instead?

**Comment by BigAl607** [comment]
Um, no, not at all. That's totally not what I did.
