### ISSUE TITLE
Mining Gadget not creating pathway with paver installed

### ISSUE THREAD

**Issue by Skriton** [Direwolf20-MC/MiningGadgets#119]
Installed paver mod with the expectation that it would place blocks to walk on. I'm also using the 3x3 upgrade with precision mining off. I tried having different block in inventory and on toolbar with no success.

Mod Version: mininggadgets-1.6.0
Java Version: forge-1.16.3-34.1.25

**Comment by MichaelHillcox** [comment]
That upgrade isn't fully implemented yet, the code as is should build cobble stone under the mining AOE as long as the area below it is air. It doesn't aways work and I plan to fix that at some point :P

**Comment by Skriton** [comment]
I fully understand. Other then that, I love this tool. The light effect is particularly nice. Thanks for the attention and I hope your endeavors go well.

**Comment by MichaelHillcox** [comment]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177
