### ISSUE TITLE
[Suggestion] Solidifier Upgrade

### ISSUE THREAD

**Issue by andr9528** [Direwolf20-MC/MiningGadgets#12]
An upgrade that works similar to the Freeze upgrade, but instead works on gravity affected blocks turning the first block that would fall into a matching solid block, preventing the whole stack from falling e.g

- Sand --> Sandstone
- Red Sand --> Red Sandstone
- Gravel --> Cobblestone or any other stone variant
- Concrete powder --> Concrete of matching colour

Not sure how you would/should handle some of the more unique gravity blocks (anvil & dragon egg) and any unknown falling blocks, that other mods might add.

You could have it break and replace the first gravity effected block with e.g a cobblestone, stopping the stack from collapsing.

On another unrelated note, i'm looking forward to using this mod, looks really cool, from what i have seen on Soaryn's stream.

**Comment by MichaelHillcox** [comment]
> Concrete powder --> Concrete of matching colour 
bit op.

The rest actually seem pretty logical :D

**Comment by andr9528** [comment]
Well the concrete powder would normally just have to be placed in water to turn it into its respective matching concrete, so i don't see how this would make it OP.

**Comment by MichaelHillcox** [comment]
You're not wrong, I'm sure I had a reason for saying it last night :P
