### ISSUE TITLE
[1.16.3] ATM-6 Crash to desktop when mining QuarryPlus frame

### ISSUE THREAD

**Issue by alexandrusendroni** [Direwolf20-MC/MiningGadgets#120]
When mining a QuarryPlus frame with a Mining gadget, the game crashes.

To Reproduce

    Create a new Quarry.
    Let the Quarry create the frame
    Attempt to mine a QuarryPlus frame block with a Mining Gadget.

Expected behavior
Do not change the QuarryPlus frame state OR mine/destroy the frame.

[crash-2020-11-09_18.40.19-server.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/5528923/crash-2020-11-09_18.40.19-server.txt)

**Comment by andrewsf** [comment]
https://github.com/Direwolf20-MC/MiningGadgets/blob/4cbd2a8ee772290d1ebd880cc893c44604fe66cb/src/main/java/com/direwolf20/mininggadgets/common/items/MiningGadget.java#L348

**[world.getTileEntity(...) can return null.](https://forge.yue.moe/javadoc/1.16.3/net/minecraft/world/IBlockReader.html#getTileEntity-net.minecraft.util.math.BlockPos-)**

**Comment by MichaelHillcox** [comment]
That would be really weird for that to be null, likely if the setstate is rejected. I’ll get this sorted

**Comment by MichaelHillcox** [comment]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177
