### ISSUE TITLE
[1.16.3] blocks not rendering properly under water

### ISSUE THREAD

**Issue by CursedOutlaw** [Direwolf20-MC/MiningGadgets#121]
blocks not rendering properly when mining gadget is used to mine blocks under water.

**Comment by MichaelHillcox** [comment]
Do you have a preview of this?

**Comment by MichaelHillcox** [comment]
I'm gunna go ahead and close this, I've asked around and it looks to be a MC render engine limitation for some reason even though it used to work fine. I've been told that using the *Fabulous!* mode solves the issue but it'll likely break other things and it's much harder to run for weaker systems.
