### ISSUE TITLE
[1.16.3] Visual conflict with Advanced XRay mod

### ISSUE THREAD

**Issue by odisies9000** [Direwolf20-MC/MiningGadgets#122]
I've noticed that while the x-ray mod is active, showing where the selected ore is, the mining gadget laser doesn't render.
You can see for yourself in the short youtube clip I've attached.
This is using the latest versions of both mods.
Video link : https://youtu.be/gOz40wUh4J0

**Comment by MichaelHillcox** [comment]
Huh, for once, I actually work on both of these mods... I'll look into this, it might show some major render leaks on one of our sides. (likely the xray one)

**Comment by odisies9000** [comment]
xray-1.16.3-2.5.0

**Comment by MichaelHillcox** [comment]
Not an issue, thanks for letting me know, I'll do some investigative work into this issue

**Comment by MichaelHillcox** [comment]
This is an issue with XRay, I'll get it sorted. Please submit this same issue over on my Repo so I remember to do it haha. https://github.com/MichaelHillcox/XRay-Mod/issues/new?template=bug_report.md&title=[1.16.3]%20Visual%20conflict%20with%20Advanced%20XRay%20mod The link has your title already in it, please add the same detail as above. Many thanks
