### ISSUE TITLE
ATM6 1.16.4 Lose inventory when sorting with void filter open

### ISSUE THREAD

**Issue by warriorplatypus** [Direwolf20-MC/MiningGadgets#123]
If I sort my inventory with the void filter open, I lose almost all of my inventory. When I click to sort, all of my items are removed from my inventory and appear in the filter, to include my mining laser. I have had this happen several times. This happens with white list or black list set.

**Comment by MichaelHillcox** [comment]
Sounds like a mod ignoring the `canInsert` method. What mods do you have that sort your inventory

**Comment by warriorplatypus** [comment]
It looks like the pack is using Inventory Tweaks Renewed 1.16.2-1.0.0.

**Comment by MichaelHillcox** [comment]
Hmm, could be that then, let me test it out

**Comment by MichaelHillcox** [comment]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177
