### ISSUE TITLE
Mining Gadget visual glitch

### ISSUE THREAD

**Issue by DrawingMC** [Direwolf20-MC/MiningGadgets#124]
Hi there
I am using this amazing mod in ATM6 and i have been having the issue that i cannot see any kind of visuals though it previously worked. I am just trying to get an answerif it has happened to anyone else and how i can fix it. I also have seen that Youtubers like Chosenarchitect and Lashmak have not had visuals in some parts of their videos. As stated above it worked but then it stopped and that repeated itsself, so I just felt the need to get an answer. i am not trying to waste anyone's time but please just look into it. I really love this mod and I am trying to get it's full potential!
kind regards
DrawingMC

**Comment by DrawingMC** [comment]
I have an update regarding that for sure will help fixing this!
The visual glitch is similar to post i have read on here with the X-Ray mod which made me think. I was using Netherite sight from Potionmaster in combination with Apotheosis charms which gave me permanent netherite sight that lets me see ores like you do in X-Ray! I removed the charm and relogged and BOOM! highlighting blocks and laser are back.
Hope it helps
-DrawingMC

**Comment by MichaelHillcox** [comment]
Likely a rendering leak from the other mod, please report it there as well as here :) thanks for looking into it

**Comment by MichaelHillcox** [comment]
This is on the other mod,. I just need to fix that mod
