### ISSUE TITLE
[1.16.4] Shrink Block Visual Glitch

### ISSUE THREAD

**Issue by LandonCalling** [Direwolf20-MC/MiningGadgets#125]
Playing in Enigmatica 6 where they are using Emendatus Enigmatica to unify ore gen.  When I mine an ore from this mod using the shrink block visual it will show the texture of regular stone rather than the texture of the actual ore being mined.  See pictures for more detail.  This doesn't seem to be occurring with other ore blocks (e.g. I added mystical agriculture and mining those blocks works fine.).  I should note that the fade block visual seems to be working fine.  This is my first time submitting an issue, so if I have left something out let me know.  :)
![2020-12-12_17 27 27](https://user-images.githubusercontent.com/52553841/102000893-f4893a00-3ca0-11eb-9aa8-d72db6291867.png)
![2020-12-12_17 27 29](https://user-images.githubusercontent.com/52553841/102000894-f6eb9400-3ca0-11eb-91a8-a10c56ba66ec.png)

**Comment by MichaelHillcox** [comment]
Hmm, likely a fail safe, I’ll look into this

**Comment by MichaelHillcox** [comment]
Likely just an odd mod thing as we get that texture from the block... Not sure if it's worth to much research into. Thanks for the issue though, if you can tell me what mods ore it is, I might get a change to look into it at some point. Closing for now.
