### ISSUE TITLE
Typo in item description.

### ISSUE THREAD

**Issue by GW1986** [Direwolf20-MC/MiningGadgets#126]
![MC DW20 pack - Mining Gadget 1 16 typo](https://user-images.githubusercontent.com/52787988/102698510-2d478700-423e-11eb-8376-8766c56d13c3.jpg)

Typo in Upgrade: Light Placer

Places touches, likely should be Places Torches.

**Comment by D3add3d** [comment]
Possible duplicate of #69 @MichaelHillcox said it was fixed but I just found the same issue in FTB DW20 1.16 pack, not sure about the version, will have to check.

**Comment by MichaelHillcox** [comment]
Fixed in recent pr. Thanks for the help
