### ISSUE TITLE
[Suggestion] Can we get animated laser colors maybe as an upgrade or something?

### ISSUE THREAD

**Issue by Svangen** [Direwolf20-MC/MiningGadgets#128]
Like can we get an upgrade to have a rainbow laser color and/or maybe that it emits some sort of particle or something with an upgrade

**Comment by gameplays12303** [comment]
go into the visual setting in the mod , shift click/use(menu)-visual setting (button in menu) -change laser color each bar represent a dye color,green,blue,red and there are two of them one is for the otter and the other is for the inner; turn up or down and you can change the color of the lazer  , or are you talking about dyeing the item itself is so good idea , if this isn't what you were looking for sorry

**Comment by MichaelHillcox** [comment]
Please provide more info regarding your request :D
