### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by castilio20** [Direwolf20-MC/MiningGadgets#129]
if you use the speed spell from Ars Nouveau this happen
![2020-12-23_18 15 58](https://user-images.githubusercontent.com/76228548/103016780-7413d600-44f7-11eb-9661-8d4b5e070f28.png)

**Comment by gameplays12303** [comment]
it look's like to me your going faster than the position update tick for the mod , this is normal for mostmod , when you go fast , it the same thing like the 1 tick piston glitch that causes it to leave the block behind the game doesn't update it fast enough by the time it receives it's false , there isn't much they could do ,except speed up the tick rate for the mod but that brings in more problems , i'm just wandering has this  happen with vanilla speed potions if so they could possibly increase the frequency of the position update tick 

note , what i mean by position update tick ,  this is basically updating a player position for the mod database, it doesn't exist as a command but a process you must do to keep it updated
