### ISSUE TITLE
[Suggestion] Tunneling Upgrade

### ISSUE THREAD

**Issue by andr9528** [Direwolf20-MC/MiningGadgets#13]
First mentioned by Soaryn during his stream on 15/11-19

An upgrade that would fill in the ground below the mined block or laser, should they be missing
e.g

Tunneling underground, and then hitting a ravine, instead of having to stop and build a bridge, it forms a floor beneath the laser, using a selected type of block from the inventory

**Comment by MichaelHillcox** [comment]
@Direwolf20-MC

**Comment by Direwolf20-MC** [comment]
Hrmmm. What if, instead of using a block, it build a block out of energy? :). Kind of like psi's blocks, but more permanent?

**Comment by andr9528** [comment]
It is your mod, so do as you please, creating one from energy does seem fine. 

Would be nice to have the ability to select which block to build with, out of a selection of simple blocks, e.g
- Diorite
- Granite
- Cobblestone 
- Sandstone

Having the ability would allow the player more access to blocks they like to scaffold with, instead of forcing cobblestone or stone on them. Also allows them to mark their way home easier.

**Comment by Nightcaste** [comment]
> Would be nice to have the ability to select which block to build with, out of a selection of simple blocks, e.g

Priority given to stuff in your "void junk" list, so instead of voiding it, it fills the holes with the junk
