### ISSUE TITLE
[idea] Feather upgrade

### ISSUE THREAD

**Issue by ianwijma** [Direwolf20-MC/MiningGadgets#131]
This is just an idea and I'm curious what the interest is. I'm willing to try to implement the feature.

**The idea:**

A single tier upgrade that doesn't slow you down when you fire the laser.

**Reason for the upgrade:**

If you are using a efficiency 5 upgrade, the laser if going faster than you can walk. So it would be nice to have an upgrade that allows you to walk at normal speed so its easier to keep up with mining.

**Comment by MichaelHillcox** [comment]
Honestly this is less of an intended feature as it is an intended bug fix. I'd prefer it doesn't slow you down but some odd things with MC and holding right click on an item has caused it all to be a bit odd...

**Comment by ianwijma** [comment]
Aahh check, Same effect is there indeed when eating. But maybe it could be a feature, where the "bug fix" sits in a upgrade? :P Just thinking out loud. Because mining when walking full speed is a convenient.

**Comment by InFuRiTy** [comment]
I second that!!!!
I wouldn't even care if it was end game/hardcore recipe too!!!
