### ISSUE TITLE
Mining Gadgets and Tetra progression breaking

### ISSUE THREAD

**Issue by ArukaAlter** [Direwolf20-MC/MiningGadgets#132]
The Mining Gadget can mine forged pillars, bypassing the need for a tier 5 Tetra hammer
Currently tested on 1.16.4 with Mining Gadgets 1.7.1, Tetra 3.4.0 and Forge 35.1.29

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21

**Comment by ArukaAlter** [comment]
The mining level requirements were apparently lowered around 1.20.1, so it's a non-issue currently.
