### ISSUE TITLE
Can't target coral fans for harvesting

### ISSUE THREAD

**Issue by Kriiks** [Direwolf20-MC/MiningGadgets#133]
Minecraft 1.16.4 and Mining Gadgets 1.7.1 
Seems like mining laser has issues targeting coral fans. I do have silk touch upgrade and I can harvest alive coral blocks, but laser just can't target fans at all and goes straight through and harvests blocks behind it.
edit: it actually does work, but it really needs very specific distance fairly far away from block, if you move even a bit further or a bit closer to actual expected mining distance, it stops working.

**Comment by gameplays12303** [comment]
is the block an entity? if it is that is why direwolf20 (mod owner) has banned mining any entities for stabilization purposes      , you can't mine a chest  , i don't even think your able to break a torch with the mod (if you do the you likey mind under it ) ,and if he dose i can see why with a torch it's simple delete it (in code that is what's happening) and give item to player (without chatting it)

**Comment by Kriiks** [comment]
Explains why I couldn’t harvest a beehive (was wondering about that), but coral fans are not block entities. 
If you have any kind range module installed, it makes it really tricky to target them. Without range module it’s a bit better, but in all cases you have to be at max mining range to be able to target and mine them. 
Just wondering can something be done to make them more easily targetable, as first it just felt like you can’t target coral fans at all.

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
