### ISSUE TITLE
[suggestion] vain mine like upgrade

### ISSUE THREAD

**Issue by gameplays12303** [Direwolf20-MC/MiningGadgets#136]
i would like some type of upgrade that would highlight or just mine the ores if the curser is on a ore , it would be similar to vain mine but take much more then normal  power or cost a lot to make i can't think of making an image , what i'm hoping by requesting this is that i don't continue to waste power on blocks i'm not mining for and the 1 by 1 isn't efficient , it want the upgrade to be flippable (can be turn on off ) without changing the main way of selecting mining size

**Comment by MichaelHillcox** [comment]
closed in preference of #166
