### ISSUE TITLE
Placing conflicting upgrades into the Modification Table deletes the second one

### ISSUE THREAD

**Issue by aaronhowser1** [Direwolf20-MC/MiningGadgets#137]
For instance, if a Gadget has the Tier 1 range upgrade, placing a Tier 2 or 3 one deletes it.

This is using mininggadgets-1.7.1

**Comment by MichaelHillcox** [comment]
Hmmm, don't think I've ever tried that, I'll check it out.

**Comment by himehimetan** [comment]
Confirming this is correct.

- Mining gadget 1.7.1

- Forge 35.1.36

My gadget has tier 1 fortune, drag and drop tier 2 fortune deletes it, vice versa,
