### ISSUE TITLE
Freeze upgrade destroys water logged tile enitys 

### ISSUE THREAD

**Issue by tubaplayer112** [Direwolf20-MC/MiningGadgets#139]
There was a mana and artifice area in a village that was waterlogged including some of the mana and artifice blocks. when using the mining gadget with the freezer upgrade  it turned the waterlogged entities into packed ice. I tested it with a vanilla chest and the same happened.

**Comment by Zarkazm** [comment]
This bug has returned in the 1.19.2 version of Mining Gadgets.
