### ISSUE TITLE
[Suggestion] Vein Upgrade

### ISSUE THREAD

**Issue by andr9528** [Direwolf20-MC/MiningGadgets#14]
When specifically targeting an ore, mine any connected of the same type. 
This should potentially come at some higher energy cost, to balance the help it gives with mining for ores. 

Would also be a great way for mod pack creators to allow them to gate vein mining behind something, as they can create their own recipe for the upgrade with mods like CraftTweaker

**Comment by ItsTheBdoge** [comment]
Personally I wouldn't want to see a vein ore upgrade, plus you are expecting every mod dev to include ore tags to the blocks which is not likely to happen. I would love to see some sort of API though for people who want to add their own upgrades

**Comment by MichaelHillcox** [comment]
Unfortunately I asked dire for this and it was a hard no. Thanks for the suggestion though :D

**Comment by MichaelHillcox** [comment]
Also @ItsTheBdoge an API would be relatively annoying to do as currently the upgrade system is quick and dirt. Having an API would require us to define a set spec that all upgrades use at least one of aka: onBreak, onMine, onActivation, etc Basically a load of events we'd loop though and call. Then we'd have to figure out what to do with it. Yeah it's quite some workload but It might be a thing after release and the dev on the mod slows back down.
