### ISSUE TITLE
Weird behavior with Mining Laser in Mekanism Induction Matrix

### ISSUE THREAD

**Issue by whizvox** [Direwolf20-MC/MiningGadgets#140]
Minecraft Version: 1.16.4
Mining Gadgets Version: 1.7.1
Mekanism Version: 1.0.19.446

I can charge the Mining Laser in just about every block that supports the charging of energy-based items. However, Mekanism's Induction Matrix seems to be an exception to this, and results in strange behavior.

The Induction Matrix will accept the Mining Laser in either of its slots, but nothing happens. Energy-based items from other mods work just fine.

![2021-01-29_13 06 26](https://user-images.githubusercontent.com/8813286/106327503-129c0100-6233-11eb-9689-46148d755f67.png)

Shift-clicking the Mining Laser into the Induction Matrix results in what initially appears to be a duplication glitch. However,  the top item is actually a ghost item that immediately disappears when clicked on.

![2021-01-29_13 06 41](https://user-images.githubusercontent.com/8813286/106327616-4a0aad80-6233-11eb-8d37-112fde85e193.png)

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
