### ISSUE TITLE
JEI and Modification table deletes Gadget

### ISSUE THREAD

**Issue by bloodtap** [Direwolf20-MC/MiningGadgets#142]
Using the modification table with cheat mode in JEI can delete the item, as JEI overlaps with the location the inventory slot.

**Comment by bloodtap** [comment]
![image](https://user-images.githubusercontent.com/3780260/106887432-fae0d480-6699-11eb-94b4-6d9f72fc84ac.png)

**Comment by MichaelHillcox** [comment]
Thanks! I must have missed this, the fix will be released in the next update
