### ISSUE TITLE
Magnet Upgrade Unexpected Behavior

### ISSUE THREAD

**Issue by 347Online** [Direwolf20-MC/MiningGadgets#143]
I hesitate to call this a bug per se.

I'm playing in the 1.16 Direwolf20 Modpack, and I notice that using the Mining Gadget with the Magnet Upgrade, seems to be incompatible with Simply Backpacks Auto-Pickup.

I assume this is because the items skip being entities and are placed straight into the inventory, never giving SimplyBackpacks a chance to process it as an Event.

It would be awesome to be able to use the Backpack to automatically store the huge resource collection the gadget produces.

One possible solution that I can think of instead of skipping spawning the entities, would be to let them spawn, but teleport them to the player's position. This would have the added benefit of allowing the magnet effect to still have a use, even while the player's inventory is full.

**Comment by MichaelHillcox** [comment]
This actually used to work, I'll look into it thanks

**Comment by MichaelHillcox** [comment]
Just checked and this seems to be still working, please leave more if if it's still not working for you, it might be another mod blocking the event. For now I'm going to close this issue.
