### ISSUE TITLE
In-Game Visual Glitch (Green Box)

### ISSUE THREAD

**Issue by GoodieProp** [Direwolf20-MC/MiningGadgets#145]
Whenever I use the mining gadget a green box appears on my screen. This only happens when I use a shaders pack, more specifically the complementary shaders pack. I was told in the complementary shaders discord that this is happening because the mod might be colliding with optifine's shader pipeline. 

![mining_gadget_green_block_visual_glitch](https://user-images.githubusercontent.com/57167634/111231399-2fa84b80-85b7-11eb-9008-88093e212e90.png)

**Comment by MichaelHillcox** [comment]
Fancy graphics?

**Comment by GoodieProp** [comment]
What do you mean?

**Comment by MichaelHillcox** [comment]
Are you using Fancy Graphics settings? Could you also share what shader pack you are using and if you're using optifine?

**Comment by MichaelHillcox** [comment]
It's likely a incomparability between optifine and the way the box is rendered. Or it's because you're using fancy graphics. Sorry but I can't do much here.
