### ISSUE TITLE
Addon mod

### ISSUE THREAD

**Issue by starforcraft** [Direwolf20-MC/MiningGadgets#148]
Hello,
I wanted to make a addon mod (Mining Upgrades :) ) for Mining Gadgets because I really like the mod. But I want better Upgrades for the Mining Gadgets because then its more cool and OP >.<. The addon mod should add new Upgrades to the Mining Gadget like 9x9 Mining or Efficiency 500 or 2x Block Drops and other cool upgrades but the problem is I can't extend the "Upgrade" enum class soo.. I asked in the Forge Discord and they said I should ask the Dev and im here lol

**Comment by mertgoksel** [comment]
+1 I am here for this reason too.

**Comment by MichaelHillcox** [comment]
There would a lot of rewriting required to allow for something like this as I'd need to implement the upgrades in an event driven way rather than the way do it currently. Please list the type of thing you'd like to do so I can attempt to support them through an API

**Comment by starforcraft** [comment]
> There would a lot of rewriting required to allow for something like this as I'd need to implement the upgrades in an event driven way rather than the way do it currently. Please list the type of thing you'd like to do so I can attempt to support them through an API

I would like to add more Mining Gadget Upgrades with that mod
