### ISSUE TITLE
battery upgrade gives infinite free power

### ISSUE THREAD

**Issue by redgoblin88** [Direwolf20-MC/MiningGadgets#15]
upon getting the mining gadget and an energy upgrade, put the upgrade in the tool and notice how you get a slight bit of free energy. i assume this is intentional

but the bug comes when you remove and intert the upgrade. each time the upgrade is added the free energy is re-added

so if you have a tier 3 battery upgrade (which is what i tested with and found the bug with) and inset it, each time you get 1,500RF free, so if you take it out and put it in 4 times you get 6,000 free RF

**Comment by MichaelHillcox** [comment]
Haha, this is great. The reason it does this is to avoid an issue where the gadget would be stuck on the last upgrade battery. Say you had a tier 3 and put a tier 2 in, you'd still have 10m in the gadget so we've pushed a small update. I think the simplest way to sort this is to figure out why the `simulate` var didn't work or just put the insert to 1rf making it pointless to do this as it would take a million clicks yet to fill tier one :P
