### ISSUE TITLE
black sreen when using mining gadget

### ISSUE THREAD

**Issue by JackThomson15** [Direwolf20-MC/MiningGadgets#151]
any time me or anyone else on the server use a mining gadget the user and anyone near-by's screen becomes black

[https://i.gyazo.com/4a23c0b095c3b21708f1e1156097e6af.mp4](url)

**Comment by Flekrad** [comment]
Disabling the mod Smoothfocus seemed to fix this in the TNP Limitless pack 
Client side mod so each person will need to do it ,
As if you disable yours , others nearby that "havent" will "still" see black screen

**Comment by Shindur** [comment]
The mod author of Smoothfocus is aware of the issue and is looking into it as well.
https://github.com/NotUnfound/SmoothFocus/issues/7

**Comment by MichaelHillcox** [comment]
He's fixed it :+1: closing now
