### ISSUE TITLE
Screen goes black when mining with the mining gadget mk3

### ISSUE THREAD

**Issue by Keshmo71** [Direwolf20-MC/MiningGadgets#152]
![unknown](https://user-images.githubusercontent.com/85594101/121276060-f15fb700-c89b-11eb-8293-49968480946f.png)
Title shows says the issue any known fixes?

**Comment by goku727** [comment]
Happend the same problem with MK1

**Comment by MichaelHillcox** [comment]
It's another mods issue from the looks of things #151

**Comment by goku727** [comment]
Seems to be solved in last version of smoothfocus
