### ISSUE TITLE
Control Key conflict in Minecraft 1.16

### ISSUE THREAD

**Issue by ghost** [Direwolf20-MC/MiningGadgets#153]
I'm playing the FTB Endeavour 1.4.0 Modset on Minecraft 1.16 and have both a mining gadget and the building and exchanging gadgets. I wanted to bind all their menus to the same key so that I would have one key meaning 'access the settings for this device I'm holding' but if I set both the 'Settings Menu' of the building gadgets and the 'Open Mining Gadget's Settings' for MiningGadgets to the same key (doesn't seem to matter which) then neither work.

**Comment by MichaelHillcox** [comment]
I'll look into this, I know we've had the same request on building gadgets as well

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
