### ISSUE TITLE
Mining Gadget doesn't unlock Lost Trinkets

### ISSUE THREAD

**Issue by NielsPilgaard** [Direwolf20-MC/MiningGadgets#154]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/2515
Question on Lost Trinkets tracker: https://github.com/owmii/Lost-Trinkets/issues/80

The Mining Gadget does not unlock [Lost Trinkets](https://www.curseforge.com/minecraft/mc-mods/lost-trinkets) when mining. I asked for help relaying the issue on the Lost Trinkets tracker, and got this helpful response:

> Lost Trinkets is using a [mixin on `Block#harvestBlock`](https://github.com/owmii/Lost-Trinkets/blob/70560a9b652a4c586e0e3ab07bfcd4e2123a0042/src/main/java/owmii/losttrinkets/core/mixin/BlockMixin.java#L22) to detect when a block is broken. I'm not 100% sure why it's not using the Block Break event tbh (perhaps it had issues with trinkets dropping when they should due to the block break being canceled after it fired for the mod?). It gets called in `PlayerInteractionManager#tryHarvestBlock(BlockPos pos)`.
> 
> Mining Gadget seems to replace the target block with a tile entity that stores the block state.
> When [`RenderBlockTileEntity#removeBlock()`](https://github.com/Direwolf20-MC/MiningGadgets/blob/3a0db5cf8f1b0b91a7b666c275e69e81222a8b86/src/main/java/com/direwolf20/mininggadgets/common/tiles/RenderBlockTileEntity.java#L368) is called, it doesn't seem to update the actual state of the block in world before getting the drops, I think this is okay, but it doesn't raise a block break event either... It does raise a block break event when [checking for harvestibility](https://github.com/Direwolf20-MC/MiningGadgets/blob/master/src/main/java/com/direwolf20/mininggadgets/common/items/MiningGadget.java#L186) though, which might cause some weird things to happen if a mod is listening in on that event to do something when a block is broken.
> 
> I think Mining gadget could do something similar to what the PSI mod does, where it temporarily sets the currently held item of the player to the tool to use for [harvestability checks](https://github.com/Vazkii/Psi/blob/b53891d603fc47c7cf1cf5a279052a2d50a8db4d/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java#L80-L164) and when breaking the block and then turning it back (the latter doesn't happen in psi but it probably should, oops...).
> 
> In summary I'd take a look at the `PlayerInteractionManager#tryHarvestBlock(BlockPos pos)` method and try to call that some how with the desired mining tool being in the main hand for actually mining a block. As for checking for harvestibility without doing a break block event, could do something like what [the PSI mod does](https://github.com/Vazkii/Psi/blob/b53891d603fc47c7cf1cf5a279052a2d50a8db4d/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java#L137-L163), calling `IForgeBlock#canHarvestBlock` with the tool in the main hand will raise the proper events without breaking the block.

Do you guys think it would be possible to add compatibility with Lost Trinkets, given that information? :)

**Comment by MichaelHillcox** [comment]
I'll try and rework how all this works soon :+1:

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
