### ISSUE TITLE
Compatibility Issue Immersive Portals (Forge)

### ISSUE THREAD

**Issue by dasrukh** [Direwolf20-MC/MiningGadgets#155]
Not sure which end this is on, my apologies if it's not something you can resolve. I am having a mod compatibility issue with Immersive Portals (forge) and Mining Gadgets. Every time I use the mining gadget to mine a 3 by 3 of blocks I get these errors and a fatal from the output log. [https://pastebin.com/5pATBGKx](url) It doesn't show any of the dematerialization of the blocks on a 3 by 3, light placer don't quite work right but I think that's due to the stutter as well its quite stutter-y because it's constantly generating that output of errors and fatals. It does render on the 1 by 1 with less stutter. When I disable Immersive Portals (Forge) mod everything with the mining gadget works normally.

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
