### ISSUE TITLE
Block dupe with "Void Junk" upgrade and Astral Sorcery's "Spatial Manipulation" perk.

### ISSUE THREAD

**Issue by Meegooo** [Direwolf20-MC/MiningGadgets#156]
If you have "Void Junk" upgrade installed on the mining gadget and start breaking any block (without finishing breaking it), items will be sent into your inventory. Spam right click and get free stuff. Works for both filtered and unfiltered items. Happens with just Astral Sorcery and Mining Gadgets (+dependencies) installed.

Steps to reproduce:
1. Get "Spatial Manipulation" perk from Astral Sorcery.
2. Install "Void Junk" upgrade into mining gadget.
3. Right click blocks

Versions:
Minecraft: 1.16.5
Forge: 36.1.31
Mining Gadgets: 1.7.5
Astral Sorcery: 1.13.12

Related issue from ATM6 modpack https://github.com/AllTheMods/ATM-6/issues/870

**Comment by Meegooo** [comment]
Was reading other issues, and noticed an interesting observation here https://github.com/Direwolf20-MC/MiningGadgets/issues/154
> It does raise a block break event when checking for harvestibility though, which might cause some weird things to happen if a mod is listening in on that event to do something when a block is broken.

Sounds like it might be related. But still I'm confused as to why it only happens with "void junk" upgrade

**Comment by KevDWhy** [comment]
This issue also exists in the Direwolf20 1.16 mod pack version 1.11.0

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
