### ISSUE TITLE
Fade and Shrink animations freak out.

### ISSUE THREAD

**Issue by IdealIdeas** [Direwolf20-MC/MiningGadgets#157]
Modpack Enigmatica 6
No optifine, no extra mods.

Sometimes blocks dont get fully mined and will start to freak out. 

Shrink causes the blocks to constantly go full size and shrink super fast and repetitively.

Fade causes the blocks to blink in and out of existence and sometimes be so faded you cant actually see the block.

Would also love to just use the standard breaking animation, its easier to tell when its about to break.

**Comment by MichaelHillcox** [comment]
Please can you attach videos of this behaviour, for this issue, and your others :+1:

**Comment by IdealIdeas** [comment]
https://user-images.githubusercontent.com/3318728/128138442-cfc8818f-880e-41dd-93da-6c671768c282.mp4

**Comment by XXXJetfireXXX** [comment]
tbh I'd also like to have a standard breaking animation as an option.

**Comment by MichaelHillcox** [comment]
I have a funny feeling this is to do with server TPS as this doesn't happen in Single player from my testing

**Comment by XXXJetfireXXX** [comment]
Yeah it looks like a TPS issue

**Comment by MichaelHillcox** [comment]
If it is TPS there is basically nothing I can do about this. Even having a standard break animation, it would still be bound to TPS issues

**Comment by XXXJetfireXXX** [comment]
Though I still like the normal breaking animation more than the shrinking and fading ones, aesthetically I mean. But I'm not sure if it's possible for you to add it since I'm not a modder haha x)
