### ISSUE TITLE
Insufficient mining level for stone and ores 

### ISSUE THREAD

**Issue by NathanH759** [Direwolf20-MC/MiningGadgets#159]
Hi,
I am playing on the latest version of the Direwolf20 pack which is running mining gadgets v1.7.5.
When using the mining gadget it appears that the mining level isnt high enough for stone and ores?
It works on dirt but anything above mining level (stone) it doesn't work?
When trying to use it on a black in front of me the laser never fires and it sounds almost like the tool is "stalling" and frequently makes the same noise every second. When not looking at a block the laser fires but then when turning to a block such as stone the block disappears but then doesn't drop the block.

Screenshot attached showing the information at the top showing the mining level isn't high enough. 
I am on a multiplayer server and they have said there is no restriction in place on this item, its just bugged. 

Any ideas?
Thanks
![Mining Gadget ](https://user-images.githubusercontent.com/45152674/131383187-eeb183bf-1520-4478-8256-1e98471b5568.png)

**Comment by MichaelHillcox** [comment]
Walla or what ever mod that might be (there is a few... looks more like TOP?) won't support the way the gadget works. We break the blocks after the laser has finished breaking down the blocks. The item itself does not have a mining level thus shows that it's not thr right tool. Hope that helps
