### ISSUE TITLE
[suggestion] bell ringing

### ISSUE THREAD

**Issue by redgoblin88** [Direwolf20-MC/MiningGadgets#16]
minecraft now has vanilla bells and have a feature in which if you shoot them with an arrow they will ring

it would be a neat little feature that if you hit a bell with the laser that it rings it (since it cant mine it as its a tile entity)

**Comment by MichaelHillcox** [comment]
Hmm, seems a tad out of scope but we'll see what @Direwolf20-MC thinks

**Comment by Direwolf20-MC** [comment]
Meh. I don’t think it’s necessary. Sorry. Want to keep the code as clean as possible.
