### ISSUE TITLE
Waterlogged Floating Botania Flower

### ISSUE THREAD

**Issue by eractnod** [Direwolf20-MC/MiningGadgets#161]
Mining Gadget 1.7.5 on Forge and Minecraft for 1.6.5 (DireWolf20 mod pack)
If you water log a floating pure daisy from Botania, then wait for the surrounding water to turn to snow.  Mine the snow with a mining gadget with a freezing upgrade.  It will turn the water logged daisy to packed ice.  Tried with water logged stairs, but it left the stairs water logged and did not turn them to packed ice.
![2021-11-15_18 47 41](https://user-images.githubusercontent.com/5204558/141870781-c210f64a-f369-4952-8590-5c46de13161a.png)
![2021-11-15_18 47 27](https://user-images.githubusercontent.com/5204558/141870782-eb77b130-1478-4282-8f43-cda862316a40.png)
Repeated this twice.

**Comment by MichaelHillcox** [comment]
Oh... that's not good, I'll look into this, waterlogging is a pain and I thought I fixed this!

**Comment by AWDoBaun** [comment]
I have a possibly related symptom.
"lava-logged" mekanism heat generators get turned into obsidian by the Freezing upgrade. Observed in 1.18 version in the recent dw20 pack. file version mininggadgets-1,11,0 from the timestamps inside the JAR it looks like this version is from March 31 2022.

**Comment by MichaelHillcox** [comment]
Interesting... how do you lava-log a block?

**Comment by AWDoBaun** [comment]
This particular block ( ) generates RF when surrounded by lava, but in addition to being surrounded it can be lava-logged ( share a space with a source block of lava, just like you waterlog a slab),  for a small bonus to the RF production
![image](https://user-images.githubusercontent.com/12954977/169658371-c0c65556-eca0-41d7-a5f6-f4eff8f24c1c.png)
![image](https://user-images.githubusercontent.com/12954977/169658464-a875399f-65e7-4bac-966b-c2ec536e1857.png)

**Comment by BL00DW0LF** [comment]
I see this is marked as fixed in a future update, I wanted to add another test case to confirm.  I had this issue in the latest version of the 1.18 DW20 pack.  Somehow my Magmatic Dynamos got waterlogged, and the mining laser (with ice upgrade) overwrote them with packed ice.

**Comment by Direwolf20-MC** [comment]
Should be resolved
