### ISSUE TITLE
can't close little upgrade screen 

### ISSUE THREAD

**Issue by Yvorie90** [Direwolf20-MC/MiningGadgets#163]
![image](https://user-images.githubusercontent.com/73123597/147864706-8fe694e0-b5fa-43ec-b48f-dbf6f89a0a25.png)
 
I can't close/hide the little screen on the right side, I tried everythings maybe I'm just dumb but please help x)

**Comment by MichaelHillcox** [comment]
This is not part of Mining Gadgets, this is part of the FTB Quests mod. If you wish to remove the sidebar, you'll need to go into your quest book and un-bookmark the quest (the pin icon) :+1:

**Comment by Yvorie90** [comment]
thanks<3
