### ISSUE TITLE
Minor bug in 1.16.5

### ISSUE THREAD

**Issue by NicholasRB** [Direwolf20-MC/MiningGadgets#165]
Short video showcasing the bug:

https://www.youtube.com/watch?v=6oNGj6qlmH4

All that is happening is the gadget does not mine when you start from in the range of the gadget in the main hand of the player. If you start out of range and walk into mining range, it will go and mine the blocks. As soon as you stop though, the same bug occurs.

**Comment by MichaelHillcox** [comment]
Can't reproduce
