### ISSUE TITLE
[1.18.1] Amethyst clusters not dropping proper number of shards

### ISSUE THREAD

**Issue by Sn4rb** [Direwolf20-MC/MiningGadgets#168]
Amethyst clusters are supposed to drop [4 shards minimum](https://minecraft.fandom.com/wiki/Amethyst_Cluster#:~:text=Breaking%20an%20amethyst%20cluster%20with%20a%20pickaxe%20drops%204%20shards%20while%20any%20other%20method%20of%20breaking%20it%20yields%202%20shards.) when broken with a pickaxe, but when mined with a mining gadget they yield only 2, even with a fortune upgrade installed. The game is treating it as if they're being broken with the wrong tool.

Modpack: Enigmatica 8 v1.0.4
Minecraft 1.18.1
Forge 39.0.14
Mining Gadgets 1.10.2

**Comment by Chocorean** [comment]
Also, `Charged Amethyst` items from Hex Casting are not affected by the Fortune upgrade! (DW20 1.18 pack) I guess it comes from the same issue, but if someone stops by for this specific issue, I solved it using a vanilla pickaxe enchanted with Fortune III

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
