### ISSUE TITLE
Feature Request: Dank Storage integration.

### ISSUE THREAD

**Issue by Boomflex** [Direwolf20-MC/MiningGadgets#17]
As per conversation with Dire on Discord would it be possible to have Dank Storage integration?

https://www.curseforge.com/minecraft/mc-mods/dank-storage

**Comment by Direwolf20-MC** [comment]
Should be do able. :). It would work like building gadgets does.

**Comment by xoption** [comment]
Force us to make an upgrade to get this integration! ;D
