### ISSUE TITLE
Mining Gadget compatibility for Dadobug1111's Bedrock Ores

### ISSUE THREAD

**Issue by dadobug1111** [Direwolf20-MC/MiningGadgets#172]
The mining gadget breaks bedrock ores once and sets block to air. Bedrock ores are not suppose to turn to air when broken, instead they can be broken infinitely without losing the block.

if you put line 481 of [MiningGadgets/src/main/java/com/direwolf20/mininggadgets/common/tiles/RenderBlockTileEntity.java](https://github.com/Direwolf20-MC/MiningGadgets/blob/master/src/main/java/com/direwolf20/mininggadgets/common/tiles/RenderBlockTileEntity.java) in an if statement that only runs if state is NOT in [Exclusion Block Tag], that _should_ allow me to add my blocks to the tag and fix it, if I am reading the code right.

Thank you for considering this!

https://github.com/dadobug1111/DadobugBedrockOres - The mod in question

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
