### ISSUE TITLE
Applying and removing a battery upgrade on a Mining Gadget charges it by 1 FE

### ISSUE THREAD

**Issue by James103** [Direwolf20-MC/MiningGadgets#173]
With Mining Gadgets 1.11.0 and Charging Gadgets 1.7.0, using a Modification Station to add or remove a Battery Upgrade on a Mining Gadget will charge its internal energy storage by 1 FE every time.

To reproduce:
1. Install the aforementioned mods or the Direwolf20 1.18 mod pack.
2. Get a Modification Station and a energy-depleted Mining Gadget.
3. Get a Battery Upgrade. It does not matter the tier.
4. Add the Battery Upgrade to the Mining Gadget.
5. Notice it has been charged by 1 FE.
6. Remove the Battery Upgrade from the Mining Gadget.
7. Notice it has been charged by 1 FE.

This could be used to very slowly charge the gadget so a player can mine a block for free, but this is very slow (less than 100 milliFE/t at best)

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21

**Comment by James103** [comment]
Looks like this was always and still is an issue.

You're still sending 1 FE to the Mining Gadget when its max energy updates, here:
https://github.com/Direwolf20-MC/MiningGadgets/blob/e11c7e6f60057c9bf476c97efa260bbe6bff993f/src/main/java/com/direwolf20/mininggadgets/common/capabilities/EnergyStorageItemstack.java#L34

This is also present in 1.20.4 and earlier versions: https://github.com/Direwolf20-MC/MiningGadgets/blob/2aa38783c86efc3db6c82bda07c92977112a7f47/src/main/java/com/direwolf20/mininggadgets/common/capabilities/EnergisedItem.java#L30

And since at least 1.15:
https://github.com/Direwolf20-MC/MiningGadgets/blob/5c601ead60fd2d68a6b8e4fbe66fee1c972b54fa/src/main/java/com/direwolf20/mininggadgets/common/items/EnergisedItem.java#L29
