### ISSUE TITLE
Mining bypassing XP storage.

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/MiningGadgets#175]
When mining with the laser and getting coal or any other ore that gives you XP and you have an Insightful Crystal (or any other XP Holding Trinket) and Auto collect is turned on it will go to the player instead of the Crystal.

This was done on the Direwolf 20 1.8.1 pack update 1.2.0

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
