### ISSUE TITLE
Bug in combination with FTB Ultimine

### ISSUE THREAD

**Issue by dBHI-zz** [Direwolf20-MC/MiningGadgets#178]
Hello,

there seems to be a bug in combination with FTB Ultimine.

Expected behaviour:
Either all the Blocks marked by Ultimine are mined or only the targeted block gets mined. 

Acutal bahaviour:
All blocks marked by Ultimine get instantly deleted.

Best regards,
dBHI

**Comment by RipleyHyena** [comment]
Still an issue in 1.20.1

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
