### ISSUE TITLE
[1.18] - Particles pulled by magnet upgrade with left hand

### ISSUE THREAD

**Issue by Gemsanches** [Direwolf20-MC/MiningGadgets#179]
While playing as left handed (or with the mining gadget in the shield slot) I noticed the particles from the magnetic upgrade still goes to the right hand.

**Comment by nat212** [comment]
I am experiencing this issue as well. Playing on the latest Direwolf20 1.18 pack (version 1.4.1) Attached is a screenshot demonstrating the issue.

![2022-06-10_17 07 21](https://user-images.githubusercontent.com/42024975/173223812-d2e6ab82-3841-4e02-b601-7957480a693f.png)

**Comment by Direwolf20-MC** [comment]
Should be fixed now :)
