### ISSUE TITLE
Localized name for block.mininggadget.renderblock.name

### ISSUE THREAD

**Issue by Halfdeaf** [Direwolf20-MC/MiningGadgets#18]
When you use the mod with One Probe the unlocalized name of the render block is considerably longer than the usual block name you are mining and it can get kind of distracting due to the One Probe box expanding and contracting rapidly when mining a bunch of blocks with efficiency upgrades

**Comment by MichaelHillcox** [comment]
Well, stop looking at it? Duh... And yeah, it's been on my todo list for a little bit but very low priority for me. Been working hard on those upgrades :+1:

**Comment by Halfdeaf** [comment]
Understandable, it's a minor annoyance :D. Awesome work by the way the gadget feels so good

**Comment by MichaelHillcox** [comment]
You've got dire to thank to for the way the mod feels :D

**Comment by Halfdeaf** [comment]
I figured, I did thank him personally on the Tropicraft server this weekend but I doubt he saw it due to the insanity that was the closing ceremonies. So if you see this the mod is great Direwolf :D
