### ISSUE TITLE
[1.18.2] Render error on multiplayer

### ISSUE THREAD

**Issue by jinks** [Direwolf20-MC/MiningGadgets#185]
When using a mining laser on a multiplayer server, the block vanish animation does not render, the block just pop out of existence after a moment. (When mining very hard blocks you can see the WAILA tooltip change to the "do not use" one, so it *does* doe the switch to the proper render block.)

Here is a log from single player: https://zerobin.net/?f0fe4114dbf964bf#d53l+0p5A1Wlt4u0bDfFMeqjubkoiIM4UCkIb0vjzDk=

And here from multiplayer: https://zerobin.net/?013cfefe1b8336cc#jvGUWEoVdEA6pq3QEGse6i9Yi4an9Y5RgMqAqtVgX2U=

These were taken immediately after each other. There's unfortunately not much information besides the NPE on the BlockableEventLoop.

**Comment by jinks** [comment]
Some better logs:

We recreated the problem on a LAN world. The animation renders properly for the host, but not for the client.

Host log: https://mclo.gs/Z6sEPB1
Client log: https://mclo.gs/Ox4Q96N

The MP session starts at around `[27Jun2022 19:24:02`

**Comment by jinks** [comment]
After some more testing, this turns out to be some kind of mod conflict. If I disable Cyclic the render works. Gonna pop over to their gh.

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
