### ISSUE TITLE
Mining Gadgets’ miner’s lights break Potion Master’s sight effects

### ISSUE THREAD

**Issue by Nevrai** [Direwolf20-MC/MiningGadgets#189]
My eternal charm of AllthemodiumSight stopped working all of the sudden, which was coincidentally after I installed the light placer upgrade, which causes the gadget to place small, non-solid lights if it’s dark around you, in my mining gadget. Turns out, these lights, for some reason, cause the outline around ores during [Potion Master’s](https://www.curseforge.com/minecraft/mc-mods/potionsmaster) sight effect not to appear, and when nearby miner’s lights are removed, the outline returns.

I did take a video, but my GeForce Experience is, for some reason, broken, and all videos are unwatchable. But essentially, to describe it the best I can, I had my AllthemodiumSight charm activated (which gives you a potion effect that outlines nearby ores of that type—in this case, allthemodium ore) and found allthemodium ore, but there was no outline around it. After about an hour and a half of troubleshooting, I realized that removing nearby lights placed by the mining gadget with the light placer upgrade solves the issue. I don’t know why or which mod is at fault here (whether it’s Mining Gadgets or Potion Master), but at least I found the cause.

I tested this in a clean install of the latest version of the [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/) modpack, 0.4.26, with no extra mods, shaders, data packs, or resource packs added, and the same issue occurred. Also tested on version 0.4.25, where the same weird bug happens. Also reported on All the Mods 7’s issue tracker [here](https://github.com/AllTheMods/ATM-7/issues/1383).

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (version 0.4.25 & 0.4.26)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Mining Gadgets:** 1.11.0 (latest for 1.18.2)
* **Potions Master:** 40.1.10 (latest)

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
