### ISSUE TITLE
Feature Request: Swap left and right mouse buttons

### ISSUE THREAD

**Issue by Huene** [Direwolf20-MC/MiningGadgets#20]
I am so used to left click to mine, right click to place, that when firing the laser is a right click it really messes with my head to the point that I'm discouraged from using it.  

Could you add a way to swap the mouse buttons so that left click mines?

Thank you folks, otherwise love it

**Comment by Direwolf20-MC** [comment]
Sorry that’s not possible with how mc works. Mc doesn’t send a packet to the server when a player left clicks.
