### ISSUE TITLE
Mining Gadget voids upgrades when changing cosmetic form

### ISSUE THREAD

**Issue by mblakew** [Direwolf20-MC/MiningGadgets#200]
Given a mining gadget with upgrades applied to it, if you were to change the cosmetic form by putting the laser in a crafting table it will void all upgrades currently on the laser.

**Comment by MichaelHillcox** [comment]
What is a cosmetic fom? Please provide versions of the mods you're running and a step by step reproduction guide

**Comment by mblakew** [comment]
I am running mining gadgets 1.11.0, minecraft version 1.18.2. Reference this image showing what I mean by a cosmetic change. Reproducable by adding upgrades to a minnig gadget laser, then putting the laser into a crafting table and crafting the laser with a new cosmetic skin. 
![image](https://user-images.githubusercontent.com/32109522/209761130-4325ee54-933a-4a6b-be82-e94de2568d3f.png)

**Comment by biochemie** [comment]
Confirming this is also present in Mining Gadgets version 1.11.1 on Minecraft 1.18.2. Unclear if this is intended behavior or not, but certainly not pleasant to discover after just putting some expensive upgrades into it.

**Comment by MichaelHillcox** [comment]
Looked into this quickly. This will be down to what ever modpack you're playing. There is no recipe in Mining Gadgets that allows for converting between gadgets.
