### ISSUE TITLE
Shrink Block Render issue in MG 1.13.0 (also 1.12.1) or MC 1.19.2

### ISSUE THREAD

**Issue by volrathstormborn** [Direwolf20-MC/MiningGadgets#201]
There was a change in either Minecraft 1.19 or Mining Gadgets 1.12+ that broke the animations on a certain set of blocks in the Dokucraft texture packs that was not an issue in MC 1.18.2 with MG 1.11.1.

Attached screenshots of the deepslate in both versions with 1.18 working and 1.19 shrinking the Tuff but all of the deepslate disappears (same for deepslate ores).  Does not happen with deepslate cobble or bricks.

Attached the textures as well in case there is something wrong with them, but they are exactly the same in both versions of your modpacks so not sure the issue would be with the image files.

[deepslate.zip](https://github.com/Direwolf20-MC/MiningGadgets/files/10270970/deepslate.zip)
![MC 1-18-2 with MG 1-11-1](https://user-images.githubusercontent.com/119960041/208734231-3cd49452-7cbc-4e97-9ef8-41356887e37b.jpg)
![MC 1-19-2 with MG 1-13-0 cobble](https://user-images.githubusercontent.com/119960041/208734234-a91e20e3-5d30-4a1c-9967-b243f7e74e8e.jpg)
![MC 1-19-2 with MG 1-13-0](https://user-images.githubusercontent.com/119960041/208734236-1623d39d-7412-4e60-97f7-c6f4ce10d14a.jpg)

**Comment by rickhovanec** [comment]
Image names did not come over.  First one is 1.18.2, second is 1.19.2 with the cobble, and last is 1.19.2 with the missing deepslate blocks while the Tuff is shrinking correctly in the same targeted group.

**Comment by SyndiShanX** [comment]
The issue here is that the shrinking animations don't seem to work with Custom Models

**Comment by Direwolf20-MC** [comment]
Please re-open if this is an issue still in 1.21
