### ISSUE TITLE
The range upgrade takes diamond pickaxes with goodies like efficiency 4 attached as a part to make the 3x3 upgrade

### ISSUE THREAD

**Issue by gzcwnk** [Direwolf20-MC/MiningGadgets#202]
The range upgrade takes diamond pickaxes with goodies attached as a part to make the 3x3 - bug I suggest

direwolf20 s12e3

**Comment by Direwolf20-MC** [comment]
This is the case for all mods with this kind of function. Best I can suggest is be more careful :)
