### ISSUE TITLE
Volume slider not working in 1.19

### ISSUE THREAD

**Issue by xaelith** [Direwolf20-MC/MiningGadgets#203]
Just started the Direwolf20 1.19 modpack, and when I try to set the volume to 25% for the Mining Gadget Mk. 3, it reverts back to 100%. Setting to 0% works fine, but anything else resets to 100% once the gadget's settings are exited.

**Comment by schmintendo** [comment]
This also happens in AllTheMods 8.

**Comment by MichaelHillcox** [comment]
Think this is fixed, please let me know if it's not
