### ISSUE TITLE
Light Placer inconsistently updating clients while playing on a server

### ISSUE THREAD

**Issue by nebulazorua** [Direwolf20-MC/MiningGadgets#205]
While on a server, the Light Placer upgrade isnt updating clients that the Miner's Light is there. It only updates when you try to place a block on the Miner's Light, then it updates the client.
This issue is not on Singleplayer

https://streamable.com/29x92o

**Comment by MichaelHillcox** [comment]
Interesting, thanks for the report

**Comment by nebulazorua** [comment]
If it helps, the server has [Canary](https://www.curseforge.com/minecraft/mc-mods/canary), so that may be influencing things?

**Comment by ukmcplyr** [comment]
I think I've run into this or a similar bug whilst putting together a 1.19.2/Forge 43.2.6 modpack.

As in the OP, client-side is fine. But on a server, mining lights aren't visible until the chunk is unloaded/reloaded or a block update is forced. Also the block breaking/shrinking animation doesn't render; mined blocks just disappear once broken.

I've narrowed down one mod incompatibility: Ad Astra. Removing that mod (v1.12.5) from [this mod set](https://pste.ch/rocuhidise.sql) solves the light placement/rendering bugs I'm seeing.

Adding a [final set](https://pste.ch/onixebodok.css) of client-side only mods breaks mining gadgets again as above, annoyingly.

Should I file a new bug for all of this or update here if/when I track down the other mod incompatibilitie/s I'm seeing?

**Comment by Direwolf20-MC** [comment]
This must be a cross mod compatibility problem, because i'm simply calling setblock like I do for most other things :).
