### ISSUE TITLE
Can't mine upclose with Mining Gadget

### ISSUE THREAD

**Issue by Adrianisss** [Direwolf20-MC/MiningGadgets#207]
I am playing Stone Block 3 and i have to be alteast five blocks to be able to mine with the gadget, if i am closer no no lase is emited and  the sound is repeated( a short video with the problem https://www.youtube.com/watch?v=gk23xTQReF0 ). Is this intended?

**Comment by Kadah** [comment]
Also uncounted this on the DW20 1.20 pack, but not to this extreme, usually when nearly face against the surface. Happens a lot with >1b sized blocks like bamboo.

**Comment by kaplantm** [comment]
i'm seeing the exact same issue using an mining gadget MK1 on an atm9 0.2.61 server

**Comment by Direwolf20-MC** [comment]
I can't duplicate this bug - i have to assume theres another mod causing it. If you can help figure out what other mod might be getting in the way i'll try to find a resolution :)
