### ISSUE TITLE
Mining laser sound effect issue

### ISSUE THREAD

**Issue by FurryPop61** [Direwolf20-MC/MiningGadgets#208]
Playing DW20 1.19.2 v1.2.0 on a Bisect Hosting server.  Laser sound effect activates correctly the first time laser is used but the sound doesn't end and stays anchored to the location it was first used. The laser sound continues in that spot and doesn't activate after that for any other uses of laser until client has been disconnected/session ended and then reconnected to server. Other laser functionality is fine.

**Comment by FurryPop61** [comment]
thanks, i know a new update was released in the past couple days but haven't updated yet.  i'll do that now and reply back.  thanks for getting back to me so quickly

**Comment by MichaelHillcox** [comment]
Pretty sure this is released, let me know if it's still happening
