### ISSUE TITLE
Lasers behind blocks are rendered in front of them

### ISSUE THREAD

**Issue by tyrope** [Direwolf20-MC/MiningGadgets#21]
As can be seen in [Episode 15 of your Forgecraft S11 playthrough from 12:17 forward](https://youtu.be/hNXSiYXWMMs?list=WL&t=737), when soaryn mines with his laser, his laser is rendered on your screen, despite him being behind blocks.

Surely his laser at that point shouldn't be rendered. ;)

**Comment by Direwolf20-MC** [comment]
It’s an easy fix. I’m just gonna have to figure out if it was changed on purpose or not :).
