### ISSUE TITLE
Incompatibility with other mods

### ISSUE THREAD

**Issue by robit4** [Direwolf20-MC/MiningGadgets#210]
It seems that the "not enough animations mod with see body in first person mod" makes you hold 2 mining lasers at the same time... like this 
![2023-03-14_10 18 43](https://user-images.githubusercontent.com/126712560/225086294-7b05b46e-54e3-4d95-a5f6-11aa597cc455.png)
It doesn't make sense can that be fixed please?

**Comment by MichaelHillcox** [comment]
What Mining Gadgets version, and not enough animations version please?
