### ISSUE TITLE
Fabric 1.13.1 infinity power

### ISSUE THREAD

**Issue by aruss69xd** [Direwolf20-MC/MiningGadgets#212]
Gadgets wont lose any power when charged, worked on 1.13.0 (All of Fabric 6 modpack)

**Comment by csBlackWolf** [comment]
I can confirm the infinity power issue with the "All of Fabric 6" modpack.

**Comment by MichaelHillcox** [comment]
Mining Gadgets isn't on fabric, please report it to the correct mod author
