### ISSUE TITLE
Reducing/Removing freeze particles

### ISSUE THREAD

**Issue by Lord-Volkner** [Direwolf20-MC/MiningGadgets#213]
The freeze particles are really overwhelming. I like to greatly reduce them or even turn them off, but I don't want to turn off all particles.

Thanks,
V

P.S. I did find this as a previous issue, which it seems was fixed, but I can't figure out the fix.
https://github.com/Direwolf20-MC/MiningGadgets/issues/71

**Comment by MichaelHillcox** [comment]
They shift right click menu has a slider for the particles

**Comment by Lord-Volkner** [comment]
> They shift right click menu has a slider for the particles

Awesome, thank you. I thought that meant something else.
