### ISSUE TITLE
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177

### ISSUE THREAD

**Issue by Majorwoops** [Direwolf20-MC/MiningGadgets#214]
Fixed in 1.7.1: https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3121177

_Originally posted by @MichaelHillcox in https://github.com/Direwolf20-MC/MiningGadgets/issues/108#issuecomment-732421168_

**Comment by MichaelHillcox** [comment]
I'd need a crash log

**Comment by Majorwoops** [comment]
I don’t get a crash log just the error I attached to the post, it doesn’t
open up all the way

**Comment by visionintruetype** [comment]
this still happens with mining gadgets 1.11.1, heres a log from when i tried to start my game. im also playing vault hunters 
[crashlog.txt](https://github.com/user-attachments/files/15920126/crashlog.txt)

**Comment by Direwolf20-MC** [comment]
Can you try without rubidium and see if you crash ?

**Comment by visionintruetype** [comment]
yup, still happens

**Comment by Direwolf20-MC** [comment]
And without birderless gaming window ?

**Comment by visionintruetype** [comment]
mhm, its windowed

**Comment by Direwolf20-MC** [comment]
Does that mean without borderless window it doesn’t crash?

**Comment by visionintruetype** [comment]
well no it crashes either way, i dont think it has anything to do with the window

**Comment by Direwolf20-MC** [comment]
I'm sorry I can't reproduce this, and haven't seen anyone else reporting it. There must be something unique in your setup here.
