### ISSUE TITLE
3x3 mining 1.20.1

### ISSUE THREAD

**Issue by x-j0nnay-x** [Direwolf20-MC/MiningGadgets#219]
when i am using 3x3 mode down at y-57 deepslate and tuff  area seems like the laser will mine the top 3 and two of the middle the left on and center all the way. but the right middle and bottom row does not mine and comes back. i also do not have any efficacy addons yet just lucky 2 and 3x3

**Comment by x-j0nnay-x** [comment]
Just checked it still does not work. I looks like 3x3 is broken no matter where I use it.

**Comment by x-j0nnay-x** [comment]
im also using a mod call controllable, dont know if that is the issue or not though. as using normal mod work fine.

**Comment by MichaelHillcox** [comment]
https://github.com/Direwolf20-MC/MiningGadgets/assets/12798904/10ecfa27-c36e-4555-ad6a-692623bb2fd0

Not sure I follow, here is a video of me mining with the 3x3 at the bottom of the world. If someone could attach a video of them having the issue, that would be super helpful.

**Comment by x-j0nnay-x** [comment]
i just checked with fresh install of mods on my computer seems to work. i must have had something messed up. works great. thanks for the help!
