### ISSUE TITLE
1.20 Mining Gadget crashing game.

### ISSUE THREAD

**Issue by IamStig** [Direwolf20-MC/MiningGadgets#221]
Hi Dire, playing Unstable 1.20 and I have had a number of crashes while using the mining gadget.
This is a pastebin of the latest crash log https://pastebin.com/kFUHWZJR

The only other info I have is that I used the miner to do world gen mining (as you do) quite a bit without issue. All the crashes occurred in my chunk loaded base (I think I mined world gen in chunk loaded area below my base with no issue).
I at first suspected I might have been mining a waystone but I now believe it may be interaction with a mod called Energized Power that is the issue.   
EDIT MG version 1.15.0

**Comment by MichaelHillcox** [comment]
Please update to `1.15.2`
