### ISSUE TITLE
no drops from themining laser on server

### ISSUE THREAD

**Issue by Swegay** [Direwolf20-MC/MiningGadgets#222]
1.18.2 
forge 4.2.10
works fine in singleplayer
does not work on my arclight server

**Comment by Swegay** [comment]
and I see no errors in server log

**Comment by MichaelHillcox** [comment]
`arclight` is likely the issue.

**Comment by Swegay** [comment]
how would we know

> `arclight` is likely the issue.

**Comment by Swegay** [comment]
> By not using it

how does it even work tho

**Comment by Swegay** [comment]
> By not using it

but sir can't we find a fix for that ?🦕🦕🦕

**Comment by Swegay** [comment]
uh very sad to be unable to play with that mod
gotta look for other options
