### ISSUE TITLE
[Suggestion] "Block type"-based precision mode

### ISSUE THREAD

**Issue by Tr3c3** [Direwolf20-MC/MiningGadgets#225]
As for now, the Mining Gadget's Precision Mode only allows to switch between true (stop mining after breaking a single block) and false (standard behavior, a.k.a. LASER **ALL** THE BLOCKS!). 

I think it'd be useful to have a third mode (or fourth, if both "match material" and "match ore" criteria are desirable) where the laser would keep breaking blocks as long as they match the starting one's type (ore, stone, logs, dirt, etc) or specific material (iron, gold, copper, etc). This feature would also work well with #166, since the gadget would allow the user to laser through all the stone blocks while tunneling, and then allow harvesting whichever ores they exposed.

**Comment by Direwolf20-MC** [comment]
I think thats outside the scope of this mod :D
