### ISSUE TITLE
[Bug] Animation bug when shifting

### ISSUE THREAD

**Issue by keckrich** [Direwolf20-MC/MiningGadgets#226]
Version - 1.15.3

When using the minging gadget and pressing shift the laser beam animation instantly moves to line up with a crouched player. Same when uncrouching. However, it takes a little time for the character and mining gadget to move to the new position. This is especially noticeable when rapidly crouching and uncrouching.

If this bug isn't worth fixing that's understandable.

**Comment by Direwolf20-MC** [comment]
Yea it’s a long standing bug. Unfortunately the location of the laser is based on the players eye position which jumps (like the laser does) when pressing or releasing shift. 

It’s probably possible to fix with a lot of complexity but like you said not really worth it :)
