### ISSUE TITLE
3x3 upgrade got removed while updating

### ISSUE THREAD

**Issue by AnonnyMaus** [Direwolf20-MC/MiningGadgets#228]
3x3 upgrade got removed while updating the DW20 pack on FTB. My slider for size selection is stuck on 3x3, but I can't extract the module to further upgrade it (nor can I change back to 1x1).
<img width="461" alt="image" src="https://github.com/Direwolf20-MC/MiningGadgets/assets/144595185/bdccbea9-4b8c-4d79-9f95-009ccc17e610">
<img width="571" alt="image" src="https://github.com/Direwolf20-MC/MiningGadgets/assets/144595185/1a2ac54c-2df1-4b91-8ad4-875754f2013e">

**Comment by dataclear** [comment]
I have the same issue.

Seems like the tag for the upgrade I have is `three_by_three`, but when I add it in a test world it's `size_1` (and presumably `five_by_five` / `size_2` respectively).

I was able to fix it by changing the tag in level.dat, removing the 3x3 module then re-adding.

**Comment by Direwolf20-MC** [comment]
You'll likely need to install a new one, sorry about that! Does it let you install a new 3x3?

Alternatively if you manually update the mod it may fix it.
