### ISSUE TITLE
Block Breaking Particle Effects Emitting at Right Hand instead of Left

### ISSUE THREAD

**Issue by Judo101** [Direwolf20-MC/MiningGadgets#229]
When left handedness is set as a skin customization option in client settings, the block breaking particle effects (block textured particles coming from what's being mined) soak into the right hand instead of the left hand.

The gun and beam emit from the left hand just fine, but the particles do not. I checked with another player on the server and the handedness is correct, **_but the laser AND particle effects are emitting from the right hand instead_**. When handedness is set to right, it all appears correctly.

This was apparently fixed in two separate issues: #32 #52 

![2023-10-22_14 28 19](https://github.com/Direwolf20-MC/MiningGadgets/assets/17147536/779132d2-81b2-41f9-bb9b-d29269a3d856)
![2023-10-22_14 28 34](https://github.com/Direwolf20-MC/MiningGadgets/assets/17147536/8ffa19c9-ee82-40ce-a107-bc4112628bba)

**Comment by MichaelHillcox** [comment]
What minecraft and mod version is this?

**Comment by Judo101** [comment]
> What minecraft and mod version is this?

1.20.1 Java edition

**Comment by Direwolf20-MC** [comment]
Should be fixed in the next version :)
