### ISSUE TITLE
Mining Laser Not Working Properly After Update

### ISSUE THREAD

**Issue by AyameWolf** [Direwolf20-MC/MiningGadgets#231]
After updating to 1.20 1.3.1 the mining laser is no longer allowing me to place it in 1x1 mode.

**Comment by MichaelHillcox** [comment]
Could you attach a screenshot / video of your issue? Also, please attach a log so I can see what mods you're running with

**Comment by AyameWolf** [comment]
How do I get the log?

**Comment by MichaelHillcox** [comment]
instance/logs/debug.log

**Comment by AyameWolf** [comment]
![Screenshot 2023-10-29 105857](https://github.com/Direwolf20-MC/MiningGadgets/assets/149313572/d7344aca-4539-4fa0-a6ae-c752258787d6)

**Comment by AyameWolf** [comment]
The log is 1 MB too big to upload.

**Comment by AyameWolf** [comment]
![20231029_110922](https://github.com/Direwolf20-MC/MiningGadgets/assets/149313572/37c0f091-50cd-4956-9cee-30cbc77b07ce)

**Comment by AyameWolf** [comment]
[debug-1.log.gz](https://github.com/Direwolf20-MC/MiningGadgets/files/13198464/debug-1.log.gz)

**Comment by Direwolf20-MC** [comment]
It looks like the 3x3 upgrade got lost. Can you put a new one in and it should re-enable the button?

**Comment by AyameWolf** [comment]
I'll try that.

**Comment by AyameWolf** [comment]
It worked although I didn't have to make a new upgrade. Placing it in the modification table and removing and replacing the upgrade fixed it. Thank you.

**Comment by Direwolf20-MC** [comment]
Cool thanks!
