### ISSUE TITLE
[1.20.1] 3x3 not working correctly.

### ISSUE THREAD

**Issue by Uskoe** [Direwolf20-MC/MiningGadgets#232]
Instead of mining all 9 blocks at once the 3x3 upgrade does it one by one, starting at the bottomright then making its way up and eventually mining the middle block before the remaining 4 other blocks can be mined. Causing the upgrade to go from 3x3 to a 2x2.

**Comment by MichaelHillcox** [comment]
Could you take a short video of your issue?

**Comment by Uskoe** [comment]
I am running 125 other mods. I don't know why it didn't cross my mind that maybe one of the mods i'm using aren't compatible with the mining gadget mod. This is the latest version (1.15.5) of the mining gadget mod on 1.20.1.
[https://youtu.be/yjjC-u73kak?si=XRPxQRXO8JMHJDYX](https://youtu.be/yjjC-u73kak?si=XRPxQRXO8JMHJDYX)

I decided to run it on vanilla 1.20.1. This is also the 1.15.5 version of the mod.
[https://youtu.be/FYu7CJImglA?si=QeaTSoMxwbgV06px](https://youtu.be/FYu7CJImglA?si=QeaTSoMxwbgV06px)
So yes, it is one of the mods im running.

These are all the mods i'm running. Due to this being 
        - ad_astra 1.15.4
        - ad_astra_giselle_addon 5.8
        - aiimprovements 0.5.2
        - alexscaves 1.0.6
        - alexsmobs 1.22.6
        - ambientsounds 5.2.24
        - appleskin 2.5.1+mc1.20.1
        - architectury 9.1.12
        - attributefix 21.0.2
        - balm 7.1.4
        - bcc 4.0.8
        - betterchunkloading 1.20.1-2.2
        - bettercombat 1.8.1+1.20.1
        - betterf3 7.0.1
        - betterfpsdist 1.20.1-4.0
        - betterpingdisplay 1.1
        - bookshelf 20.1.6
        - botarium 2.2.0
        - callablehorses 1.3.0.1
        - cataclysm 1.0
        - cataclysm_delight 1.0.0
        - cataclysmiccombat 1.1
        - charginggadgets 1.11.0
        - chat_heads 0.10.22
        - chefsdelight 1.0.3-forge-1.20.1
        - citadel 2.4.7
        - cloth_config 11.1.106
        - collective 6.72
        - combatroll 1.3.0+1.20.1
        - computercraft 1.108.4
        - connectivity 1.20.1-4.6
        - corgilib 4.0.0.4
        - corpse 1.20.1-1.0.5
        - creativecore 2.11.7
        - ctov 3.3.6
        - cupboard 1.20.1-2.1
        - curios 5.4.0+1.20.1
        - customskinloader 14.18.1
        - diagonalblocks 8.0.2
        - diagonalfences 8.1.2
        - dummmmmmy 1.20-1.8.5
        - easyanvils 8.0.1
        - easymagic 8.0.1
        - ends_delight 1.0.1
        - enhancedcelestials 5.0.0.2
        - epicsamurai 0.0.27.2-1.20.1-forge
        - farmersdelight 1.20.1-1.2.3
        - farsight_view 1.20.1-3.5
        - fastload 3.4.0
        - ferritecore 6.0.1
        - forge 47.2.0
        - forgeconfigscreens 8.0.2
        - forgivingvoid 10.0.0
        - fpsreducer 1.20-2.5
        - friendlyfire 18.0.5
        - fullbrightnesstoggle 3.0
        - geckolib 4.2.4
        - getittogetherdrops 1.3
        - globalpacks 1.16.2_forge
        - gpumemleakfix 1.20.1-1.6
        - guardvillagers 1.20.1-1.6.3
        - handcrafted 3.0.5
        - hitindication 1.3.1
        - industrialforegoing 3.5.9
        - insanelib 1.12.0
        - inventoryhud 3.4.18
        - inventorysorter 23.0.1
        - ironbows 1.20.1-FORGE-1.9
        - ironchest 1.20.1-14.4.4
        - ironfurnaces 4.1.3
        - itemphysic 1.6.15
        - jade 11.6.3
        - jeed 1.20-2.1.4
        - jei 15.2.0.27
        - jeresources 1.4.0.238
        - jumpboat 1.20.0-1.0.5
        - kiwi 11.1.1
        - krypton 0.2.3
        - limitedchunks 1.8
        - logprot 1.4
        - majruszsdifficulty 1.8.1
        - minecraft 1.20.1
        - mininggadgets 1.15.5
        - mixinextras 0.2.0-beta.8
        - mlib 5.1.2
        - moderately_enough_effect_desc 1.0.0
        - moonlight 1.20-2.8.52
        - moredragoneggs 4.0
        - netherportalfix 13.0.0
        - nethersdelight 1.20.1-4.0
        - not_enough_gamerules 1.20.1-r1.5.3
        - nyfsquiver 1.18.1-0.7.0
        - okzoomer 3.0.1
        - overloadedarmorbar 1.20.1-1
        - parry 2.5.0
        - passablefoliage 8.1.0
        - patchouli 1.20.1-81-FORGE
        - playeranimator 1.0.2-rc1+1.20
        - progressivebosses 3.9.4-mc1.20.1
        - puzzlesaccessapi 8.0.7
        - puzzleslib 8.1.5
        - rebind_narrator 2.0.2
        - reeses_sodium_options 1.0.3
        - resourcefulconfig 2.1.0
        - resourcefullib 2.1.13
        - rightclickharvest 3.2.3+1.20.1-forge
        - seamless_loading_screen 2.0.3+1.20.1
        - securitycraft 1.9.8
        - servercountryflags 1.9.0
        - simpleplanes 1.20.1-5.2.4
        - simplyswords 1.51.5-1.20.1
        - smoothchunk 1.20.1-3.3
        - sophisticatedbackpacks 3.18.65.935
        - sophisticatedcore 0.5.100.457
        - spruceui 0.1.2+1.20.1
        - stackablepotions 1.0.0
        - textrues_embeddium_options 0.1.2+mc1.20.1
        - titanium 3.8.23
        - toofast 0.4.3.5
        - toolstats 16.0.4
        - trajanscore 1
        - trajanstanks 2.4
        - treechop 0.18.3
        - w2w2 1.0
        - waystones 14.0.2
        - xaerominimap 23.8.4
        - xaeroworldmap 1.36.0
        - yet_another_config_lib_v3 3.0.1+1.20

**Comment by biochemie** [comment]
> I am running 125 other mods. I don't know why it didn't cross my mind that maybe one of the mods i'm using aren't compatible with the mining gadget mod. This is the latest version (1.15.5) of the mining gadget mod on 1.20.1. https://youtu.be/yjjC-u73kak?si=XRPxQRXO8JMHJDYX
> 
> I decided to run it on vanilla 1.20.1. This is also the 1.15.5 version of the mod. https://youtu.be/FYu7CJImglA?si=QeaTSoMxwbgV06px So yes, it is one of the mods im running.
> 
> These are all the mods i'm running. - ad_astra 1.15.4 - ad_astra_giselle_addon 5.8 - aiimprovements 0.5.2 - alexscaves 1.0.6 - alexsmobs 1.22.6 - ambientsounds 5.2.24 - appleskin 2.5.1+mc1.20.1 - architectury 9.1.12 - attributefix 21.0.2 - balm 7.1.4 - bcc 4.0.8 - betterchunkloading 1.20.1-2.2 - bettercombat 1.8.1+1.20.1 - betterf3 7.0.1 - betterfpsdist 1.20.1-4.0 - betterpingdisplay 1.1 - bookshelf 20.1.6 - botarium 2.2.0 - callablehorses 1.3.0.1 - cataclysm 1.0 - cataclysm_delight 1.0.0 - cataclysmiccombat 1.1 - charginggadgets 1.11.0 - chat_heads 0.10.22 - chefsdelight 1.0.3-forge-1.20.1 - citadel 2.4.7 - cloth_config 11.1.106 - collective 6.72 - combatroll 1.3.0+1.20.1 - computercraft 1.108.4 - connectivity 1.20.1-4.6 - corgilib 4.0.0.4 - corpse 1.20.1-1.0.5 - creativecore 2.11.7 - ctov 3.3.6 - cupboard 1.20.1-2.1 - curios 5.4.0+1.20.1 - customskinloader 14.18.1 - diagonalblocks 8.0.2 - diagonalfences 8.1.2 - dummmmmmy 1.20-1.8.5 - easyanvils 8.0.1 - easymagic 8.0.1 - ends_delight 1.0.1 - enhancedcelestials 5.0.0.2 - epicsamurai 0.0.27.2-1.20.1-forge - farmersdelight 1.20.1-1.2.3 - farsight_view 1.20.1-3.5 - fastload 3.4.0 - ferritecore 6.0.1 - forge 47.2.0 - forgeconfigscreens 8.0.2 - forgivingvoid 10.0.0 - fpsreducer 1.20-2.5 - friendlyfire 18.0.5 - fullbrightnesstoggle 3.0 - geckolib 4.2.4 - getittogetherdrops 1.3 - globalpacks 1.16.2_forge - gpumemleakfix 1.20.1-1.6 - guardvillagers 1.20.1-1.6.3 - handcrafted 3.0.5 - hitindication 1.3.1 - industrialforegoing 3.5.9 - insanelib 1.12.0 - inventoryhud 3.4.18 - inventorysorter 23.0.1 - ironbows 1.20.1-FORGE-1.9 - ironchest 1.20.1-14.4.4 - ironfurnaces 4.1.3 - itemphysic 1.6.15 - jade 11.6.3 - jeed 1.20-2.1.4 - jei 15.2.0.27 - jeresources 1.4.0.238 - jumpboat 1.20.0-1.0.5 - kiwi 11.1.1 - krypton 0.2.3 - limitedchunks 1.8 - logprot 1.4 - majruszsdifficulty 1.8.1 - minecraft 1.20.1 - mininggadgets 1.15.5 - mixinextras 0.2.0-beta.8 - mlib 5.1.2 - moderately_enough_effect_desc 1.0.0 - moonlight 1.20-2.8.52 - moredragoneggs 4.0 - netherportalfix 13.0.0 - nethersdelight 1.20.1-4.0 - not_enough_gamerules 1.20.1-r1.5.3 - nyfsquiver 1.18.1-0.7.0 - okzoomer 3.0.1 - overloadedarmorbar 1.20.1-1 - parry 2.5.0 - passablefoliage 8.1.0 - patchouli 1.20.1-81-FORGE - playeranimator 1.0.2-rc1+1.20 - progressivebosses 3.9.4-mc1.20.1 - puzzlesaccessapi 8.0.7 - puzzleslib 8.1.5 - rebind_narrator 2.0.2 - reeses_sodium_options 1.0.3 - resourcefulconfig 2.1.0 - resourcefullib 2.1.13 - rightclickharvest 3.2.3+1.20.1-forge - seamless_loading_screen 2.0.3+1.20.1 - securitycraft 1.9.8 - servercountryflags 1.9.0 - simpleplanes 1.20.1-5.2.4 - simplyswords 1.51.5-1.20.1 - smoothchunk 1.20.1-3.3 - sophisticatedbackpacks 3.18.65.935 - sophisticatedcore 0.5.100.457 - spruceui 0.1.2+1.20.1 - stackablepotions 1.0.0 - textrues_embeddium_options 0.1.2+mc1.20.1 - titanium 3.8.23 - toofast 0.4.3.5 - toolstats 16.0.4 - trajanscore 1 - trajanstanks 2.4 - treechop 0.18.3 - w2w2 1.0 - waystones 14.0.2 - xaerominimap 23.8.4 - xaeroworldmap 1.36.0 - yet_another_config_lib_v3 3.0.1+1.20

TreeChop appears to be the culprit. Just ran into this same issue myself in building a customized pack.
