### ISSUE TITLE
freeze upgrade can delete loot chests

### ISSUE THREAD

**Issue by jlp1528** [Direwolf20-MC/MiningGadgets#233]
Direwolf20 1.20.1 pack. The freeze upgrade deleted a loot chest in a pirate ship. I have not tested other tile entities, but this seems bad. It didn't even drop the items, just poof!

Edit: This is probably also why I didn't find any loot chests while cheesing an ocean monument... RIP

**Comment by Anoyomouse** [comment]
Was the loot chest a waterlogged chest?

If so, that makes sense .. I'll try this out in my testing world and seeing how bad this bug is

**Comment by jlp1528** [comment]
Yeah, the chests in underwater structures are waterlogged. I haven't looked at the code, but I can only assume it replaces water source blocks without checking if said blocks are actually waterlogged tile entities. I wonder if the evaporator from Cyclic works the same way. I hope not, as that's the next thing I'm going to try.

**Comment by Anoyomouse** [comment]
So, i've replicated the bug in the DW20 1.20.1 pack (version 1.4.0)

Looks like, yes, it find a waterlogged block, and just force-replaces it with ice, instead of "burning" off the water, I'll see if i can get a quick fix for it ready

**Comment by jlp1528** [comment]
Thank you! Do you have a rough ETA on a pack update if it is a quick fix?

**Comment by Anoyomouse** [comment]
> Thank you! Do you have a rough ETA on a pack update if it is a quick fix?

Right about now, not sure why the check was there in the first place, but it's set to delete special blocks like chests if they are waterlogged

**Comment by jlp1528** [comment]
That's very odd and does not sound good for other tile entities. Imagine building an underwater base and accidentally deleting something important, crashing your game, or possibly even corrupting your world. :|

**Comment by Anoyomouse** [comment]
Well, the gadget is force replacing blocks with block entities into ice, so i don't think you'd crash, but be incredibly sad when a block you've spent hours creating and waterlogging is suddenly a block of ice.

Also, you mentioned a good point, if the block acts like a source, but is a block entity and is not waterlogged, we totally ignore that block. :)

**Comment by jlp1528** [comment]
Thank you for fixing this, hopefully your pull request is accepted soon and I'll go exploring more to test it. I wish other mod authors/contributors would respond as quickly, though I do understand many people are very busy.

It ooks like the FTB Team has plenty of issues to go through with the new Genesis pack, as well as some Aether stuff, but hopefully a minor pack update to at least the DW20 1.20 pack can be pushed in short order.

**Comment by jlp1528** [comment]
Thank you.
