### ISSUE TITLE
Erroneous Tool Tip

### ISSUE THREAD

**Issue by swestrup** [Direwolf20-MC/MiningGadgets#235]
Using the Direwolf20 pack 1.20 so, I assume that's the latest version as I write this. The tooltip for the range addons say "Extends your range by 5 times with each tier". This implies that each tier multiplies the maximum range by 5 (that is what 'times' means!) In fact, they only increase the range by 5 per tier.

**Comment by Anoyomouse** [comment]
Added PR #237 which fixes the issue, does that make more sense? :)
