### ISSUE TITLE
[Suggestion] Mousewheel integration

### ISSUE THREAD

**Issue by rebio** [Direwolf20-MC/MiningGadgets#24]
So far you have to use the mouse, grab the slider and drag it around. What about a mouse wheel option that will in- or decrease the value when you hover over it (like Mousetweaks).

So you would not have to grab and slide the bar for the laser range, but could just hover and scroll.

**Comment by MichaelHillcox** [comment]
Sorta the same thing as clicking... haha, do the Minecraft menus do it? if they do then I can likely implement it pretty simply.
