### ISSUE TITLE
[Suggestion] Laser 3x3/7x7 should mine middle block last. 

### ISSUE THREAD

**Issue by lAimBotl** [Direwolf20-MC/MiningGadgets#240]
3x3/7x7 laser modes should mine the middle/main target block last to make 3x3/7x7 tunnels more smoothly, even if the middle block is dirt surrounded by obsidian, as a extreme example. (or at least a option/upgrade for the ability)

**Comment by Direwolf20-MC** [comment]
All blocks *should* be mining at the same speed - averaging the hardness of all blocks in the area. Is that not the case?

**Comment by lAimBotl** [comment]
It looks like it mines in rows (1 block at a time from left to right, bottom to top)

Mod Version: "1.15.6"  (I see a 1.15.7, but it is below the 1.15.6 for some reason, but it also does the same thing)
Mc version: 1.20.1
(sorry for taking 6000000 years to respond)

**Comment by xstook** [comment]
I'm experiencing the same issue. I started with the Minecolonies official modpack v1.10 for Minecraft 1.20.1, and then I added the Mining Gadgets mod to it. This was all done within Curseforge.

The odd thing is I then created a custom modpack in Curseforge and added every single mod in the Minecolonies modpack, along with the Mining Gadgets mod, and I do NOT have the issue anymore 😮 I've also tried varies versions of Mining Gadgets, and they all have the issue with the Minecolonies modpack, but they all do not have the issue with my custom modpack (with the same exact mods).

**Comment by Direwolf20-MC** [comment]
Thats weird, i can only assume its a cross mod compatibility issue. If this is repeatable in 1.21 or you can show exactly which mod is causing it, please re-open a new report :)

**Comment by lAimBotl** [comment]
Let me open my test modpack again, If I remember correctly I did test with only this mod before making this post.
-welp it is fine on its own, guess I will try to find the mod.

**Comment by lAimBotl** [comment]
Looks like whatever mod was doing it, doesn't anymore after I updated all my mods.
