### ISSUE TITLE
[Bug/feedbaack] Can't Mine "Domum Oranmentum" Blocks [1.20.1]

### ISSUE THREAD

**Issue by Mini-kun** [Direwolf20-MC/MiningGadgets#242]
It won't mine the Domum Oranmentum Idk if this a bug or a other problem but it would be nice if we can mine them with the mining gadgets.
![image](https://github.com/Direwolf20-MC/MiningGadgets/assets/46404340/0d1ab864-a7ac-4154-ba34-ccfd839ba7dd)

**Comment by Direwolf20-MC** [comment]
I'm going to assume they are block entities, so that means this is working as designed.
