### ISSUE TITLE
[Suggestion] 5x5 and 7x7 point of origin shift

### ISSUE THREAD

**Issue by penturt** [Direwolf20-MC/MiningGadgets#243]
I'm loving the option for the larger mining area, works great for clearing out areas. 

But one thing i have found annoying not sure if i'm the only one, when mining using the 5x5 or 7x7 the center point is at eye level with the player so it always mines 1 block or 2 blocks lower then the feet position of the player, constantly dropping the player if trying to walk forward and mine at the same time.

My suggestion is to maybe ad an option to allow the the shifting of the mining area in respect to the where the mining laser points at. making it simpler to mine a straight tunnel with the larger 5x5 and 7x7 options.

**Comment by Direwolf20-MC** [comment]
This is an option in the shift-right click menu :)

**Comment by penturt** [comment]
really?

**Comment by penturt** [comment]
WOW!!!! Genius!! thanks for the quick assist. btw, love all your content. watching you got me back into MC.

**Comment by Direwolf20-MC** [comment]
Thank you :D
