### ISSUE TITLE
[Idea] Gadget Discharge Station

### ISSUE THREAD

**Issue by Peekofwar** [Direwolf20-MC/MiningGadgets#245]
That the battery upgrade modules don't keep their charge when removed from the gadget causing the stored power to be lost. Would be useful if we could save this energy when upgrading the battery module by discharging the capacitors back into Forge Energy prior to removing the modules.

**Comment by Direwolf20-MC** [comment]
I don't know if I really want to add a block like that for such a limited use case :).  I think you can drain the gadget of energy in some other blocks though, like maybe a cube from mekanism

**Comment by Peekofwar** [comment]
> I don't know if I really want to add a block like that for such a limited use case :). I think you can drain the gadget of energy in some other blocks though, like maybe a cube from Mekanism

Just tried this, and you cannot discharge the Mining Gadget in the Mekanism Energy Cube. The UI doesn't even let you place the gadget in the discharge slot.

Mekanism v10.4.9
Mining Gadgets 1.15.6
