### ISSUE TITLE
[1.20.1] [Bug] Black list not deleting ores like clay or copper

### ISSUE THREAD

**Issue by jarquafelmu** [Direwolf20-MC/MiningGadgets#248]
When I put things like raw copper (or copper ore blocks) into the filter set to black list it doesn't void them. 
![image](https://github.com/Direwolf20-MC/MiningGadgets/assets/5807272/70b37a0a-b3be-4af1-b9e7-a6f20f646045)
![image](https://github.com/Direwolf20-MC/MiningGadgets/assets/5807272/44120bf4-f658-4ab3-acda-f68fd128b530)

Mod version: v1.15.6

**Comment by Direwolf20-MC** [comment]
Should be resolved in the newer versions
