### ISSUE TITLE
Game crashes when mining ores with mining gadgets

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/MiningGadgets#251]
Game crashes when mining ores with mining gadgets

Crash Log: https://gist.github.com/MuteTiefling/f27bced9c6aecfcf7470e44313c307ae

mininggadgets-1.18.0.jar 
neoforge-21.0.42-beta

**Comment by ingie** [comment]
same crash for me: 


correlation

same neoforge version, 
same building gadgets version, 
same getExpDrop ticking call failure.

**Comment by Frankiscophil** [comment]
I'm experiencing the same results with Mining Gadgets Marks 1, 2, and 3.

**Session Log:** https://pastebin.com/fDek6ZNv
**Crash Report:** https://pastebin.com/6w13vQbc
**Modpack:** Craftoria 0.0.9
**Mod Version:** 1.18.0
**Neoforge Version:** 21.0.42-beta

**Comment by Direwolf20-MC** [comment]
Neoforge update made a change :) I need to update the mod. Will get it sorted soon

**Comment by Direwolf20-MC** [comment]
Fixed in the latest version 1.18.1
