### ISSUE TITLE
New crash when mining

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/MiningGadgets#252]
Not sure what I was mining this time. 

Mod Version: mininggadgets-1.18.1

https://gist.github.com/MuteTiefling/ce5e8ac39c4fa8108ec95f4ffa1b4757

**Comment by Direwolf20-MC** [comment]
How strange ! I’ll add a null check here in next version :)

**Comment by Direwolf20-MC** [comment]
Any idea what block it was that you were mining that caused the crash?

**Comment by MuteTiefling** [comment]
I was clearing out a lush cavern, so the options are kinda limited I guess. At the same time, I finished clearing the area with no further crashes, so I'm not sure.

Maybe one of the following?
Torch
moss carpet
vines
glowberries
short grass

**Comment by Direwolf20-MC** [comment]
Weird. Let me know if it happens again.  Meanwhile I’ll just add a null check ;)
