### ISSUE TITLE
Building gadgets charging station continues wasting fuel after mining gadget is fully charged

### ISSUE THREAD

**Issue by TheAGamePlayer** [Direwolf20-MC/MiningGadgets#27]
I can't really show this with a png, but I realized if I didn't take the mining gadget out of the building gadget's charging station, that it would keep using up coal even after the mining gadget is fully charged. Taking the mining gadget out of the charging station will only then make fuel consumption stop.

**Comment by MichaelHillcox** [comment]
This would be a Building Gadgets issue logically? There is likely some mess up in how we're checking if the gadget is full. Could you open this there instead?

**Comment by TheAGamePlayer** [comment]
Will do

**Comment by MajorTuvok** [comment]
@MichaelHillcox I'm pretty sure that this is not a Building Gadgets issue. The Energy implementation used by Mining Gadgets is definitly very weird - without debugging I can't verify, but I would not be surprised if it does not confirm to the IEnergyStorage contract.

Related issue is [Direwolf20-MC/BuildingGadgets#441](https://github.com/Direwolf20-MC/BuildingGadgets/issues/413) and possibly also #28
