### ISSUE TITLE
Energised Item does not read data from Server

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/MiningGadgets#28]
In [Direwolf20-MC/BuildingGadgets#441](https://github.com/Direwolf20-MC/BuildingGadgets/issues/413#issuecomment-557254517) I notice that the EnergisedItem never reads data from the passed in stack. Instead `getEnergyStored` **writes** the cached energy to the stack, overwriting whatever was in there.

I don't think this is the cause of the linked issue, but it might produce weird behaviour in the future and it should definitly be verified whether fixing this implementation fixes the linked issue.

**Comment by MichaelHillcox** [comment]
I'll check it out :+1:

**Comment by MichaelHillcox** [comment]
Fixed for 1.15, I'll do the same for 1.14
