### ISSUE TITLE
Void Junk doesn't appear to work all the time

### ISSUE THREAD

**Issue by MikeHollisJr** [Direwolf20-MC/MiningGadgets#29]
Version 1.2.3

I'm still trying to figure out what the triggering factor is, but sometimes void junk works, sometimes it does absolutely nothing, 

This is playing All the Mods 4, which is as close to Forgecraft as I can find. (LOVE bleeding edge and sometimes broken coolness)

![2019-11-22_09 29 38](https://user-images.githubusercontent.com/1078934/69434137-08b36f80-0d0b-11ea-9a2b-8222124d9d41.png)
![2019-11-22_09 30 06](https://user-images.githubusercontent.com/1078934/69434140-08b36f80-0d0b-11ea-9119-62f02793d804.png)

**Comment by Huene** [comment]
Gadget Configuration

![2019-11-22_09 39 43](https://user-images.githubusercontent.com/1078934/69434645-0bfb2b00-0d0c-11ea-9795-0f71ebf97895.png)

**Comment by MichaelHillcox** [comment]
Nothing as in it fails to mine or nothing as in it's placed in your inventory?

**Comment by Huene** [comment]
> Nothing as in it fails to mine or nothing as in it's placed in your inventory?

Right, that was a bit unclear, it successfully mines, but the void junk filter does nothing, items appear in inventory as they would without it

**Comment by MichaelHillcox** [comment]
You got it in white or blacklist?

**Comment by Huene** [comment]
> You got it in white or blacklist?

I've tried both and they have the same behavior, the black icon is showing, which I assume is the current state, but it could be the state it changes to if you click it, 

And since I haven't had reliable usage I can't tell which is the correct setting, however I have been operating under the assumption that black icon showing, is blacklist enabled

**Comment by MichaelHillcox** [comment]
So blacklist will void everything in the list, whitelist will void everything but whats in the white list. I you want to void all cobble then you'd want it in whitelist mode. It's basically a "everything but and an everything not this"

**Comment by Huene** [comment]
> So blacklist will void everything in the list, whitelist will void everything but whats in the white list. I you want to void all cobble then you'd want it in whitelist mode. It's basically a "everything but and an everything not this"

I understand the concept of a blacklist and a whitelist but the way you just phrased that makes me wonder now, so let me ask. 

does the void junk filter apply white and black list to the mining operation or to the void operation?

**Comment by MichaelHillcox** [comment]
It's kinda odd and I definitely need to clean it up so it's clear that it: Effects the Void Operation and not the mining operation. It won't leave blocks out of the 3x3 or 1x1 area. It'll simply decide which to void and which not to void. From my testing it works as intended but can be a tad confusing on what each mode does.

Say I only wanted Cobble. I'd put Cobble into the WHITELIST.
If I wanted anything other than cobble then: Cobble would be in the BLACKLIST.

I'm not trying to explain it to you, I'm trying to write it down how I programmed it haha. It's not a typical system :P

**Comment by Huene** [comment]
> It's kinda odd and I definitely need to clean it up so it's clear that it: Effects the Void Operation and not the mining operation. It won't leave blocks out of the 3x3 or 1x1 area. It'll simply decide which to void and which not to void. From my testing it works as intended but can be a tad confusing on what each mode does.
> 
> Say I only wanted Cobble. I'd put Cobble into the WHITELIST.
> If I wanted anything other than cobble then: Cobble would be in the BLACKLIST.
> 
> I'm not trying to explain it to you, I'm trying to write it down how I programmed it haha. It's not a typical system :P

Okay that is what I intuited, so that sounds good, at least to me. I'm downloading OBS so you can see the behavior in motion

**Comment by MichaelHillcox** [comment]
Alright, a video would be great.

**Comment by Huene** [comment]
https://www.youtube.com/watch?v=7FLk4I_essc

**Comment by MichaelHillcox** [comment]
Hmm, does it work on normal blocks? (mc blocks?)

**Comment by Direwolf20-MC** [comment]
Just for fun, try to disable and re-enable the void junk upgrade and see if that helps. I think some of our upgrade's NBT's are initiated correctly until you turn them on/off via the gui the first time.

**Comment by Huene** [comment]
Okay so I was able to get it to work correctly, by removing the item from the grid, 

- So I broke cobble, with cobble blacklisted
- removed cobble from the blacklist grid still left it in blacklist mode and it voided the cobble
- switched to whitelist and it correctly mined the cobblestone
- switched back to blacklist and tried to mine slate which is also in my blacklist, and it appeard in my inventory

From what I can tell for some reason things are only taking effect after removing them from the grid rather than adding them to the grid

**Comment by MichaelHillcox** [comment]
I'll see if I can reproduce the issue.

**Comment by Huene** [comment]
> I'll see if I can reproduce the issue.

Thank you, All the mods 4 on Twitch, No special configuration, Client-server setup

**Comment by Huene** [comment]
Ignore that close, I was trying to cancel a post once I ruled it irrelevant

**Comment by Huene** [comment]
Oh additionally there is no shenanigans in the server log

**Comment by dh47** [comment]
I can also confirm I'm having the same issues as @MikeHollisJr said so far.

**Comment by MikeHollisJr** [comment]
> I can also confirm I'm having the same issues as @MikeHollisJr said so far.

Just out of curiosity dh47, are you using a pack or custom mod configuration?

**Comment by dh47** [comment]
@MikeHollisJr running a heavily modified version of the unstable pack.

**Comment by sshelton** [comment]
I've found that the void filter blacklist DOES work, but ONLY if one block (any kind of block) is any slot of the void filter. As soon as I add a second block, or more, it does not void any blocks in whitelist or blacklist. If I have an empty whitelist it does void everything, and if there is one block in the whitelist it voids everything but that one block, but if I add a second or more, nothing is voided. Super bizarre behavior. This is especially annoying in ATM4 as I don't see any other item for voiding/nulling items from inventory. 

All the Mods 4, Pack 0.2.4, Forge 28.1.96, mininggadgets-1.2.3.jar. I haven't modified the pack.

I can post a video showing this on youtube if you want. I may also try making a fresh custom 1.14 pack with just forge and mining gadgets to test if it is some weird mod interaction.

**Comment by MichaelHillcox** [comment]
Hmm, that's actually super helpful, I'm sure it's a simple fix. Dire and I have been pretty busy lately. I'm going to aim for an update today maybe :D

**Comment by MikeHollisJr** [comment]
I can confirm this behavior
