### ISSUE TITLE
Laser Render doesn't respect Handedness

### ISSUE THREAD

**Issue by Limitrophic-Researcher** [Direwolf20-MC/MiningGadgets#32]
When using the skin customization options to make the Player left-handed, the laser still renders as if the Player was right-handed.

![2019-11-27_04 44 57](https://user-images.githubusercontent.com/19358958/69712359-aecaf500-10d0-11ea-9c0b-5f7b37ffce5c.png)

![2019-11-27_04 42 40](https://user-images.githubusercontent.com/19358958/69712176-64e20f00-10d0-11ea-987e-846a0ee9b669.png)

**Comment by MichaelHillcox** [comment]
I think most of us forget this exists :D I'll see if I can find the issue

**Comment by Direwolf20-MC** [comment]
I never knew it did lol :) should be an easy fix if we can detect

**Comment by KingLemming** [comment]
Sounds like a sinister issue to me.

**Comment by thecodingchicken** [comment]
It appears that this issue extends to other effects like the Freezing upgrade, so I just want to bring that to notice so it isn't missed. 
![mining_tool_image_1](https://user-images.githubusercontent.com/29822509/70101985-baed1000-1604-11ea-9bc5-01d21b28d2ba.png)
![mining_tool_image_2](https://user-images.githubusercontent.com/29822509/70101986-baed1000-1604-11ea-97f8-740ea4856f1a.png)

**Comment by MichaelHillcox** [comment]
This would be part of the same code but thanks for letting us know :+1:

**Comment by MichaelHillcox** [comment]
I've partially fixed this but as the ice is a particle and not a client render, I can't figure out how I'd take in a client side only option as I can't get it from the Mining Gadget.
