### ISSUE TITLE
[Suggestion] Solar power upgrade

### ISSUE THREAD

**Issue by ItsTheBdoge** [Direwolf20-MC/MiningGadgets#33]
This upgrade would allow a way to generate power w/o the need of a charging station

**Prerequisites of generating power**
- Sun must be out (Pretty obvious)
- Must be held out
- player must be outside/clear visual of sky

**Comment by Direwolf20-MC** [comment]
Nah :). Appreciate the suggestion but I never liked solar upgrades on items.
