### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [Direwolf20-MC/MiningGadgets#34]
We are playing All The Mods 4 and it appears that your mod is the issue for a recurring crash.

https://pastebin.com/sq2REZW8

Any further information needed just let me know

**Comment by MichaelHillcox** [comment]
Hmm, intresting, I'll take a look. The mod version would be handy.

**Comment by cauliflower69** [comment]
It's at the bottom of the crash report - buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}

Thanks

**Comment by MichaelHillcox** [comment]
I know, it's just for my reference. Thanks :D

**Comment by cauliflower69** [comment]
My bad

**Comment by Direwolf20-MC** [comment]
Hopefully that fixes it :). I couldn't reproduce, but thats my best guess.
