### ISSUE TITLE
Optional key binding

### ISSUE THREAD

**Issue by matthewwilley77** [Direwolf20-MC/MiningGadgets#36]
Please dire including the option to remap the mining laser key. as  I using the right click the shild slot for my torches, and I keep swing the gun when I go to mine.

**Comment by MichaelHillcox** [comment]
This is common but we're set on right click being the use key and the placing torches is deep into the vanilla code that we don't wish to change. Sorry for the inconvience but I'd just recommend standing a bit outside of the placing range
