### ISSUE TITLE
Mining gadget Seems to ignore mining Fatigue from Elder Guardians

### ISSUE THREAD

**Issue by russrulz** [Direwolf20-MC/MiningGadgets#37]
When i tryed to use mining gadget on the water temple after being hit with the debuff i expected it to take forever to break a block however it broke the block almost instantly as if i was not debuffed

Mining gadget had effecincy 5 upgrade silktouch upgrade magnet upgrade torch upgrade silktouch upgreade range upgrade and 3x3 upgrade

**Comment by russrulz** [comment]
mininggadgets-1.2.3.jar

**Comment by MichaelHillcox** [comment]
Seems likely, we've not taking that into consideration.

**Comment by MichaelHillcox** [comment]
Fixed soon, it'll be in the next release, also duplicate of #135
