### ISSUE TITLE
Blue Power Void Junk Bug

### ISSUE THREAD

**Issue by Manie8** [Direwolf20-MC/MiningGadgets#38]
Whenever I put a block from Blue Power in the filter for the Void Junk upgrade, it stops working all together.

**Comment by MichaelHillcox** [comment]
The filter has a few issues atm. I'm going to fix them as soon as I can

**Comment by MichaelHillcox** [comment]
Resolved in 30e99a961ed5bad23f77d95d23ee2e1fb186c17e and 08240125d1988040e1e9ff636a105b45e4b38ce8
