### ISSUE TITLE
Mining Gadget not dropping from Mod Table?

### ISSUE THREAD

**Issue by Brandon194** [Direwolf20-MC/MiningGadgets#40]
Seems like the Mining Gadget is not dropping when you break the Modification table with the mining gadget in it.

**Comment by Direwolf20-MC** [comment]
If you place the modification table back down is the mining gadget still in it ?

**Comment by Brandon194** [comment]
No, it was not in the block when I put it back down.

**Comment by MichaelHillcox** [comment]
Thanks for this one, I'll keep it open and fix it for 1.14 as well :+1:
