### ISSUE TITLE
Mining Gadget bypassing Block Protection from Dimensional Dungeons

### ISSUE THREAD

**Issue by NillerMedDild** [Direwolf20-MC/MiningGadgets#41]
Blocks in the "Dimensional Dungeons" dimension are meant to be unbreakable, so the dungeon can't be cheesed. The Mining Gadget can however break blocks in there.

####
- mininggadgets-1.2.3

**Comment by Direwolf20-MC** [comment]
Weird pretty sure I’m checking for hardness < 0 which is how bedrock works. Any idea what his mods using?

**Comment by NillerMedDild** [comment]
No idea, but I asked the author here: https://www.curseforge.com/minecraft/mc-mods/dimensional-dungeons/issues/3

**Comment by bibo38** [comment]
Just found the repository: https://github.com/AllenSeitz/DimDungeons

The mining protection is created by overriding the `canMineBlock` method of the dimension:

https://github.com/AllenSeitz/DimDungeons/blob/4feeb4e1286eff1fb5cb999b0b8f1285c01411a2/src/main/java/com/catastrophe573/dimdungeons/dimension/DungeonDimension.java#L65-L97

I've added a PR with a possible fix: #46
