### ISSUE TITLE
Void Filter Not Working

### ISSUE THREAD

**Issue by Benthedaddy** [Direwolf20-MC/MiningGadgets#42]
Right clicking an item into filter makes that item disappear FOREVER. Blacklist doesn't work at all. Whitelist only partially works.

**Comment by grandslamjmh** [comment]
I haven't seen an item disappear when right clicking into the filter, Although i've only used the blacklist option. I have noticed the Blacklist filtering is only working when 1 item is in the list.

Mod pack: All the Mods 4.

**Comment by MichaelHillcox** [comment]
Note: the issues with the filter list are now fixed but not released. I've not seen this issue happy on my end with items disappearing as the slots physically do not allow for this to happen. If you can reproduce this issue that would be very helpful but if not I'd have to assume you've had something else unrelated to this mod happen.

**Comment by Benthedaddy** [comment]
I've managed to reproduce the items disappearing. It only happens with items that are not being accepted into the filter... eg diamonds and non block items.
Bare in mind I'm running a lot of mods so may be an ore dictionary issue or incompatibility with a mod.
I'm also running instantUnify, possible that's causing it??
Heres a recording of the items disappearing on right click, ignore the clay called diamond, im messing with crafttweaker  :) 

https://youtu.be/EJlBDbvauGg

**Comment by MichaelHillcox** [comment]
Haha, it's taking the item regardless! I'll adjust the slot code to never attempt to actually take an item from the stack... but as we now allow diamonds etc this won't be an issue after the filters are updated :D

**Comment by Benthedaddy** [comment]
I've noticed it removes modded items like the chem lab uranium etc, not that you would ever have a reason to try to put it in the filter lol
So yeah, definitely needs the slot code adjusting like you said :)
Thanks for the quick reply, keep up the good work :)

**Comment by MichaelHillcox** [comment]
Released for 1.15 and will be released for 1.14 soon

**Comment by hvdklauw** [comment]
Any ETA?

Is there a roadmap somewhere with blocking issues for a 1.14 release?

**Comment by MichaelHillcox** [comment]
Literally just need to build and release, let me see if the code is stable enough for that. One sec
