### ISSUE TITLE
RenderBlock rendering error on high x coordinates

### ISSUE THREAD

**Issue by bibo38** [Direwolf20-MC/MiningGadgets#47]
# How to reproduce
- Load a word
- Teleport to the edge of the world: `/tp @p 29999940`
- Point the laser on any breakable block and move slightly.

# Expected behaviour

The block pointed at becomes green (because it's mineable)

# Actual behaviour

With slight movement the green box around the block (probably the `RenderBlock` class) doesn't align correctly or is just at the wrong block:
![Green box on the wrong block](https://user-images.githubusercontent.com/1812304/71371860-f4d18680-25b2-11ea-92d6-036221c592e2.png)

Still the laser breaks the correct blocks. Only the rendering is affected.

# Possible cause

As this effect increases, as the x coordinate (the z coordinate is probably affected the same way) distance goes up, it is probably caused by a [floating point error](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems).

P.S.: I've found this while testing the laser in the Dimensional Dungeon mod. Since the Dungeon was located at an x coordinate of around 1'500'000 the box was always on the correct block, but wobbled very violently.

**Comment by MichaelHillcox** [comment]
I'll see what I can do but it's low on the priorty list as you're at the world border :P Some mc renders don't handle this well either haha. The code being used on the render is also not optimal at all.

**Comment by Direwolf20-MC** [comment]
Still happens in 1.15, probably not something thats easy to resolve :)
