### ISSUE TITLE
[Suggestion] Add a charged Mining Gadget to the creative/JEI inventory

### ISSUE THREAD

**Issue by bibo38** [Direwolf20-MC/MiningGadgets#48]
When testing a mod I really like having a charged energy cell or item in the creative inventory and JEI, so that I can quickly test without needing to charge the block/item.

Therefore it would be nice, if the Mining Gadget could also be added as a charged variant to the creative inventory and JEI.

**Comment by MichaelHillcox** [comment]
`/give {playername} mininggadgets:mininggadget{energy:1000000} 1`
That'll give you a charged one but I could definitely look at adding a charged version. If you're in creative the gadget will always work.

**Comment by bibo38** [comment]
> /give {playername} mininggadgets:mininggadget{energy:1000000} 1

Nice to know. Much easier than getting RFTools Power alpha build for a creative energy cell, which can charge items ;D.

> That'll give you a charged one but I could definitely look at adding a charged version.

would be convenient, maybe also with all/most upgrades already installed.

> If you're in creative the gadget will always work.

Didn't work for me in a creative singleplayer world with the code on the master branch:

https://github.com/Direwolf20-MC/MiningGadgets/blob/65e75e8b4049391abe55c418af7a6ad287e0f81e/src/main/java/com/direwolf20/mininggadgets/common/items/MiningGadget.java#L281-L287

E.g. no block that doesn't pass the `canMine` function will ever get to be a Render block (and be broken by the render block).

https://github.com/Direwolf20-MC/MiningGadgets/blob/65e75e8b4049391abe55c418af7a6ad287e0f81e/src/main/java/com/direwolf20/mininggadgets/common/items/MiningGadget.java#L137-L146

And as long, as the `cost` variable doesnt get `0`, the `canMine` function will return `false`.

https://github.com/Direwolf20-MC/MiningGadgets/blob/65e75e8b4049391abe55c418af7a6ad287e0f81e/src/main/java/com/direwolf20/mininggadgets/common/items/MiningGadget.java#L344-L351

So the only way would be to set the `MININGGADGET_BASECOST` to `0`, as no upgrade can be assigned a negative value.

**Comment by MichaelHillcox** [comment]
I'll add a bypass on the canMine method, I was likely thinking on Building Gadgets as that does allow use when in creative mode :P. I'll see what I can do about JEI, of course not all upgrades can be installed at once but it would be handy to have a few pre-set versions :D

**Comment by Direwolf20-MC** [comment]
@MichaelHillcox Did this!
