### ISSUE TITLE
Crash - Ticking block entity

### ISSUE THREAD

**Issue by Xaikii** [Direwolf20-MC/MiningGadgets#49]
https://pastebin.com/dGbWjueV
Context:
Tried using the Mining Gadget to mine some Sand, while being in water.
Continuesly crashes at every Startup, can't enter my world anymore.
Modpack: All The Mods 4

**Comment by MichaelHillcox** [comment]
Hmm, thats an odd one. Water shouldn't have made a difference. I can add a protection around that method but I'm not sure why this would have crashed you. If you want to fix the crashing: I'd suggest you either delete your inventory (make a backup) if this doesn't work then try using mc edit to move your location in game so the effected block isn't loaded.

**Comment by PotatoSauceVFX** [comment]
A player on our community ATM4 server had a similar crash. They were standing on the ground and mining sand using the mining gadget as well.

Here is our server crash report: https://pastebin.com/JQiH4Kh4

**Comment by MichaelHillcox** [comment]
I'll push to get this sorted today / tomorrow for you :D

**Comment by NillerMedDild** [comment]
This crash also occurs in version 1.2.4: https://pastebin.com/7NUxUefb

**Comment by jarquafelmu** [comment]
Experienced this crash using 1.15.2 v1.3.5
[latest_3.log](https://github.com/Direwolf20-MC/MiningGadgets/files/4978280/latest_3.log)
[crash-2020-07-26_19.42.16-server.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/4978281/crash-2020-07-26_19.42.16-server.txt)

**Comment by MichaelHillcox** [comment]
Offending code: https://github.com/Direwolf20-MC/MiningGadgets/blob/1.15.2-1.3.4/src/main/java/com/direwolf20/mininggadgets/common/tiles/RenderBlockTileEntity.java#L271-L272

Thanks for you report, I'll get this fixed

**Comment by MichaelHillcox** [comment]
Fixed and released :+1:

**Comment by NillerMedDild** [comment]
Nice, thanks!

**Comment by MichaelHillcox** [comment]
Sorry it took like a year! It's been a weird one haha. Be sure to let me know if you have any other issues but please update haha! :D
