### ISSUE TITLE
Disappeared!!

### ISSUE THREAD

**Issue by OlRusty** [Direwolf20-MC/MiningGadgets#51]
i built the mining gadget in a single player world modded 1.14. i placed it in the block where you add upgrades and i went mining to get diamonds for the charging station. when i got back the gadget vanished. poof, gone, disappeared. and i checked ALL my inventories (not a lot) and no where to be found. 

Also is it possible to make it mine with normal click somehow?

**Comment by MichaelHillcox** [comment]
I'll see if I can get it to happen again

**Comment by OlRusty** [comment]
it could have also been a fluke since it happened the one time so far

**Comment by Direwolf20-MC** [comment]
Fixed in 1.15.
