### ISSUE TITLE
Laser is not drawn correctly with change of FOV

### ISSUE THREAD

**Issue by Veniak** [Direwolf20-MC/MiningGadgets#52]
The starting point of the laser coming out of the tool isnt correct when the user use for example a higher *Field of View*

**Comment by MichaelHillcox** [comment]
It's a known bug :( Just need to add some fancy math, #32

**Comment by MichaelHillcox** [comment]
also #26

**Comment by MichaelHillcox** [comment]
Will be fixed on 1.15 and 1.14 if I backport :D

**Comment by Direwolf20-MC** [comment]
Fixed by @MichaelHillcox
