### ISSUE TITLE
Crash when rendering block entity

### ISSUE THREAD

**Issue by aaron191** [Direwolf20-MC/MiningGadgets#53]
I am getting a crash any time that I try to enter my world that says Crash when rendering block entity.

I was crafting redstone blocks to create the efficiency upgrades in a crafting table, and when I selected to craft the Efficiency 2 upgrade with the crafting table full, that is when the game crashed.  

At least from what I can tell, it appears to be a problem with the Mining Gadgets charging station, but I am not sure about that.  
[crash-2019-12-29_12.51.23-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/4008442/crash-2019-12-29_12.51.23-client.txt)

**Comment by MichaelHillcox** [comment]
Building gadgets. Please report to the correct repo
