### ISSUE TITLE
Building gadgets charging station continues wasting fuel after mining gadget is fully charged

### ISSUE THREAD

**Issue by TheAGamePlayer** [Direwolf20-MC/MiningGadgets#57]
I can't really show this with a png, but I realized if I didn't take the mining gadget out of the building gadget's charging station, that it would keep using up coal even after the mining gadget is fully charged. Taking the mining gadget out of the charging station will only then make fuel consumption stop.

Version: BuildingGadgets-3.1.1b.jar for Minecraft 1.14.4

Compatibility issue with mining gadgets, just shove a used mining gadget and a stack of coal into the charging station.

**Comment by MichaelHillcox** [comment]
Although this is a Building Gadgets bug, I want to track it here as it is also an issue with out energy implementation.

**Comment by Direwolf20-MC** [comment]
This should be fixed right @MichaelHillcox ?

**Comment by MichaelHillcox** [comment]
Yup :)
