### ISSUE TITLE
Playing with "main hand left" results in beams and other effects to still be rendered to the right hand

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/MiningGadgets#58]
A user reported on Discord the following:
"i play main hand left, so beams and stuff could render from that side - instead of normal minecraft right"
I sadly don't know what main hand left is - might either be the offhand, or some weird setting which makes you swap hands...

**Comment by MichaelHillcox** [comment]
Already sorted and reported here at some point :P Await release

**Comment by MajorTuvok** [comment]
Sorry, didn 't notice
