### ISSUE TITLE
Feature Request: Building Bag

### ISSUE THREAD

**Issue by ppvolto** [Direwolf20-MC/MiningGadgets#6]
It would be interesting to have a Bag that when you have it in the Inventory, with at least one Building block (Cobble), get filled before the Void upgrade deletes the Access. Then it can be Integrated with BuildingGadges when you Build it uses Blocks from this bag First.

**Comment by MichaelHillcox** [comment]
This is going to be part of the void upgrade and will be configurable on the fly :+1: we're also not cross implementing at the moment as they're both different mods :P thanks for the suggestion though.

**Comment by Direwolf20-MC** [comment]
Use the dank/null mod :)
