### ISSUE TITLE
Claimed Chunks Mining

### ISSUE THREAD

**Issue by DinnerBeef** [Direwolf20-MC/MiningGadgets#61]
If the player is standing in a chunk that they can mine in and the mine a block in the chunk they should not be able to mine in they can mine the block (This is with ftb chunks)

**Comment by DinnerBeef** [comment]
this is with version 1.15.2

**Comment by Direwolf20-MC** [comment]
@DinnerBeef I'm gonna release a version with this fix, can you test it for me? (v1.3.1)

**Comment by DinnerBeef** [comment]
That did not seem to work. sunekear just tested it on forge craft and does the same thing ask lat if you need more info

**Comment by MichaelHillcox** [comment]
The link to FTB Utils line of code that protects it haha. I might just be missing the event.
