### ISSUE TITLE
Not able to mine redstone with mining gadget from rightclicking distance

### ISSUE THREAD

**Issue by 1persON768** [Direwolf20-MC/MiningGadgets#62]
Mod version: mininggadgets-1.3.0
MC version: 1.15.2
Forge: 31.1.18

When trying to mine redstone ore from right click distance the mining tool starts to right click the ore as rightclicking redstone ore lights the ore up.

The tool would need to be able to somehow cancel/ignore the right click to light up for the blocks that behave that way.

**Comment by Direwolf20-MC** [comment]
Fixed in 1.3.2 (Thanks @MichaelHillcox
