### ISSUE TITLE
lightplacer tooltip typo

### ISSUE THREAD

**Issue by Smollet777** [Direwolf20-MC/MiningGadgets#69]
https://github.com/Direwolf20-MC/MiningGadgets/blob/9c9dd5b3dd1783c302a98584297440906c0d32f7/src/generated/resources/assets/mininggadgets/lang/en_us.json#L66
Should it be "Places torches whenever the surroundings light level is lower than 8"?

**Comment by MichaelHillcox** [comment]
Thanks for that :+1:
