### ISSUE TITLE
[1.3.5] Upgrade slot missing from Modification Table.

### ISSUE THREAD

**Issue by Zarkov2** [Direwolf20-MC/MiningGadgets#78]
Mining Gadgets 1.3.5
Forge 31.3.30 (MC 1.15.2)

When opening the GUI of the Modification Table, the upgrade slot is not displayed. I suspect there is another method of applying the upgrades (since the GUI seems to have been intentionally altered), but I was unable to find it.

![upgrade_slot_missing](https://user-images.githubusercontent.com/9017939/78050069-17c2c200-737c-11ea-8862-85e7d9ea1a11.png)

**Comment by MichaelHillcox** [comment]
Shift click the upgrade with the gadget inside the slot to the left :+1: I worried this might be an issue

**Comment by Zarkov2** [comment]
Thanks! Not sure how many different things I tried before I gave up, but I managed to miss that one. :)
