### ISSUE TITLE
Unable to mine activated redstone

### ISSUE THREAD

**Issue by TijmenSpijk** [Direwolf20-MC/MiningGadgets#79]
When mining with the mining gadget you are unable to mine activated redstone.
This only applies when standing close enough to activate the redstone. If you have enough range the mining gadget will mine it but when you are standing to close you will activate the redstone instead of mining it.
Found this in enigmatica 5 modpack.

**Comment by MichaelHillcox** [comment]
Is this for 1.14?

**Comment by Crimix** [comment]
The issue is in 1.15, Enigmatica 5 is a 1.15 modpack. I have also encounted the issue

**Comment by TijmenSpijk** [comment]
It was in 1.15. Also opened an issue with the enigmatica 5 pack.
https://github.com/NillerMedDild/Enigmatica5/issues/155

**Comment by MichaelHillcox** [comment]
This shouldn't been an issue, hmm, what mod version?

**Comment by Crimix** [comment]
The version where I have the issue is in 1.3.1

**Comment by MichaelHillcox** [comment]
We're on 1.3.5 now https://github.com/Direwolf20-MC/MiningGadgets/blob/master/CHANGELOG.md#1152-135---2020-03-29 which I've fixed the redstone issue
