### ISSUE TITLE
Bug: Placeable Block in Offhand

### ISSUE THREAD

**Issue by ppvolto** [Direwolf20-MC/MiningGadgets#8]
You can not use the Miningadget with a Place able Item in the Offhand, wen the mining reach don't exceeds the Block Placement reach, since the Minininggadged is triggered with the same Event.

**Comment by MichaelHillcox** [comment]
Just as a reminder, the mod isn't out and is in a continual state of dev. I happen to have a funny feeling that this is intentional but I can check with dire

**Comment by ppvolto** [comment]
Yes i know its not out yet but some elements needs to be sorted out before it becomes public, and since we have the offhand it needs to be blocked from triggering, or the activation of the mining gadget needs to change. Since it so early in dev it can be decided how it works for the rest of time ;)

**Comment by MichaelHillcox** [comment]
I’ve talked to dire and the alternative causes the gadget to jump up and down in the hand as if you used an item, this isn’t nice but we cant sort it as hardcoded into mc. So this will likely always be an issue.
