### ISSUE TITLE
Filter Malfunction.

### ISSUE THREAD

**Issue by Sarge2318** [Direwolf20-MC/MiningGadgets#80]
When you have the filter open on the mining laser and you go to "sort" your inventory by clicking your middle scroll wheel it will insert everything into the filter of your laser. When you try to retrieve, all of the items disappear. I am currently using All the Mods 5 version 1.15. Minecraft Version 1.15.2 (modded) Forge- 31.1.36. This occurred 4-7-2020 at 1900 CST

**Comment by MichaelHillcox** [comment]
Wow, that's a mod conflict like no other. I'll have to look into that, sorry about your items

**Comment by Sarge2318** [comment]
> Wow, that's a mod conflict like no other. I'll have to look into that, sorry about your items

I was rather upset honestly. But, considering all the work everyone puts in I figured I would just head over to the board and see if anyone had experienced this before. When I saw that no one had listed it I thought, Wow, I found a problem. Items are always retrievable. The mod is awesome! Many props to all involved. Thanks for looking into it.

**Comment by MichaelHillcox** [comment]
It should have just caused a desysnc as the filter doesn't actually accept items so this might be a duel bug unfortunatly.

**Comment by ClintRajaniemi** [comment]
Same issue. 
ATM 5 version: 2.22
MC version: 1.15.2
forge version: 31.2.36
Mining gadgets version: 1.3.5

I'm not a Java developer, but if someone is willing to point out some potential locations where this issue could reside, I'm happy to dig in a bit.

Interestingly, the mining gadget consumed itself in it's own filter.

**Comment by MichaelHillcox** [comment]
It’s definitely a mod incompatability thing but I have no clue what mod would be causing this as all those slots have strict restrictions on what they allow in. Do any other mods in your pack have a filter like system that doesn’t have the same issue? I can use those to see if I’ve missed any steps.

**Comment by ClintRajaniemi** [comment]
> 
> 
> It’s definitely a mod incompatability thing but I have no clue what mod would be causing this as all those slots have strict restrictions on what they allow in. Do any other mods in your pack have a filter like system that doesn’t have the same issue? I can use those to see if I’ve missed any steps.

Unfortunately, it's a huge mod pack. The closest thing I could find is the Mekanism digital miner. The filter for that simply doesn't accept certain types of items. I don't know how different it is as only a single block can be entered at a time when building filters.

**Comment by MichaelHillcox** [comment]
Fixed, released on curse but might be a slow approval
