### ISSUE TITLE
Ticking player crash

### ISSUE THREAD

**Issue by PrettyLudde** [Direwolf20-MC/MiningGadgets#83]
Get these crashes when using the mining gadget. Added it to the modpack cause it´s so good. It works sometimes and then it just crashes. I´m not good with this type of stuff so asking here for help. 
Happens both in the overworld and mining dimension.

https://pastebin.com/wNwX8KMh

**Comment by BedrockLegends** [comment]
Same crash https://gist.github.com/BedrockLegends/c59308a803a1ed1bb0c22bbf60a5fccb
