### ISSUE TITLE
[1.15.2] Crash after use gadget!

### ISSUE THREAD

**Issue by Rumaruka** [Direwolf20-MC/MiningGadgets#84]
forge vestion: 31.1.44
version mod: 1.3.5
Crash report: https://pastebin.com/KkC9Kjih

**Comment by FallenAvatar** [comment]
I had the same issue. Confirmed fixed by https://github.com/MinecraftForge/MinecraftForge/pull/6633

Update forge to 31.1.73

**Comment by MichaelHillcox** [comment]
Thanks 👍 I'll look into it

**Comment by MichaelHillcox** [comment]
Closed in preference of #92, I know the issue and it'll be fixed very soon
