### ISSUE TITLE
Upgrade Slot in Modification Table is missing [1.15.2]

### ISSUE THREAD

**Issue by MoeHunt3r** [Direwolf20-MC/MiningGadgets#85]
When right clicking in the modification table there's only one slot for the Mining Gadget but no Slot to aplly the upgrades. 

Forge: 31.1.50 
Minecraft: 1.15.2 

![bug](https://user-images.githubusercontent.com/38086254/80317463-2af27180-8804-11ea-9264-0f39c05a7267.png)

**Comment by Direwolf20-MC** [comment]
Shift click the upgrades in your inventory to insert them now :)
