### ISSUE TITLE
Crash after use the mining gadget on a Fletching Table

### ISSUE THREAD

**Issue by Werneq** [Direwolf20-MC/MiningGadgets#86]
Just crafted the mining gadget, was trying on stuff when I mined the fletching table and crash
Have no upgrades.

MC: 1.15.2
Forge: 31.1.46
Mod: 1.3.5
Modpack: Valhelsia 2 vers 2.1.7 (with some extra modds)

Here the crash log: https://pastebin.com/rMWYaLXJ

**Comment by Werneq** [comment]
Actually, it crashed again while mining stone, so its not a fletching table thing.
New crash log: https://pastebin.com/K0EG5EeE

**Comment by MichaelHillcox** [comment]
Weird. I'll take a look

**Comment by MichaelHillcox** [comment]
Closed in preference of #92, I know the issue and it'll be fixed very soon
