### ISSUE TITLE
[1.15.2] Mining Gadget Disappearing fron Inventory

### ISSUE THREAD

**Issue by Alaric323** [Direwolf20-MC/MiningGadgets#87]
Forge Ver: 31.1.63 (will try updating later to see if it fixes)
Mod Ver: 1.3.5 (latest on Curseforge as of Posting)
Modpack: All The Mods 5
Environment: Single-Player World

Hi guys, having a strange bug with the mining gadget where it disappears from inventory at seemingly random.  Doesn't seem to matter what upgrades it has, as I've spawned it in after it disappears for it to disappear again maybe an hour later.  I've checked all inventories in the area around me and no sign of it.

The only thing I can think of that may trigger it is me sorting my inventory, as I tend to do that fairly often, but it definitely does not happen every time.  As far as I can tell, this is the only item that disappears on a normal basis.

If you guys have anything you want me to try, I'm more than willing to help debug.

**Comment by MichaelHillcox** [comment]
I couldn't tell you why this happens, sounds like some random mod conflict. What inventory sorting mod are you using and are you trying to sort when the inventory is full? Are you seeing it vanish or is it dropping?

**Comment by Alaric323** [comment]
Using CPW's Inventory Sorter (Latest version, V17).  I do not notice the item dropping, it simply disappears.  I ran a command block to move all loaded item instances for me to pick up when I last noticed it, and the tool wasn't in what I picked up (meaning it either despawned already or just was removed from inventory entirely).
