### ISSUE TITLE
Mining Laser Voids Blocks when Vein Mining

### ISSUE THREAD

**Issue by swestrup** [Direwolf20-MC/MiningGadgets#89]
I'm playing the FTB Omnia pack on the new launcher, and whenever I forget and hold down the tilde key when using the mining laser, it vein-mines the blocks, but voids them. They never show up in my inventory.

**Comment by MichaelHillcox** [comment]
This is a mod conflict issue, I can't resolve this. Sounds like FTB Utils is handling the event but fails but doesn't fail correctly? This could be an us issue but sounds more like and conflict issue. In my testing for this I found that if you mined with with the gadget whilst holding the tilde key it would just mine a single block.

**Comment by kandin8675** [comment]
I ran into the issue on Omnia as well and I found that the mining laser and vein mining worked with blocks that can be broken without a pickaxe i.e. dirt, logs, sand and pumpkins. It properly mined the blocks and didn't void anything. But anything that normally requires a pickaxe like stone and ores would void.

**Comment by MichaelHillcox** [comment]
I can look into it and I'll also hit up the author of FTB Utils to see if I can figure out what's going wrong

**Comment by MongoTheElder** [comment]
Is this simply because the mining gadget is not registered is not a valid mining tool and therefore there are no drops since the loot tables require a specific mining level? This would explain why blocks that do not have a minimum mining level still have drops.

**Comment by MichaelHillcox** [comment]
Yeah, this seems to have a simple solution, don't vein mine whilst using the gadget. Having the mod support vein mining would make it OP by a lot.
