### ISSUE TITLE
Doors: hard to mine

### ISSUE THREAD

**Issue by purpleposeidon** [Direwolf20-MC/MiningGadgets#9]

**Comment by MichaelHillcox** [comment]
Hard to mine?

**Comment by Direwolf20-MC** [comment]
"Fixed" 

https://github.com/Direwolf20-MC/MiningGadgets/commit/87e000eabc06012f42a4fcff6a890d2721cce79d

**Comment by purpleposeidon** [comment]
They flop about as you mine them. So do trap doors. Perhaps you could <hasnt-modded-since-1.8>cancel the interaction event</hasnt-modded-since-1.8>?

**Comment by MichaelHillcox** [comment]
:+1: for the nerd joke. I might look at canceling the interaction event but for now just ignoring the door works, I'll add a few edge cases for trap doors, etc.
