### ISSUE TITLE
[1.15.2] issues with mouse buttons 

### ISSUE THREAD

**Issue by ngdrex** [Direwolf20-MC/MiningGadgets#92]
I bind controls to my mouse and this appears to cause the mod to not load/ crash before menu
I tested this on forge 31.1.78 and with only this mod installed.
https://pastebin.com/HWsewhei

**Comment by MichaelHillcox** [comment]
Building Gadgets has had simular issues, I'll look into it for you.

**Comment by MichaelHillcox** [comment]
Fixed, will be released shortly
