### ISSUE TITLE
Laser comes out of right hand when using left hand option.

### ISSUE THREAD

**Issue by brianSites** [Direwolf20-MC/MiningGadgets#94]
If you are using the left-handed option, the laser comes out the right hand.

![image](https://user-images.githubusercontent.com/54866029/82231355-079a7e00-98fb-11ea-8cb0-e379d2304e86.png)

**Comment by MichaelHillcox** [comment]
Hmm, what version is this on?

**Comment by barbafrank** [comment]
On mining gadgets 1.3.5 - MC 1.15.2 the direction is fixed, but the laser is detached from the gun.
The particles for freezing upgrade, instead, are still broken.

**Comment by MichaelHillcox** [comment]
You would appear to have the hasit effect, although, my code should resolve the problem sooo ... hmmm

**Comment by MichaelHillcox** [comment]
Definitely fixed now, closing :D
