### ISSUE TITLE
Sand Dupe using Mining Gadget

### ISSUE THREAD

**Issue by chasesans** [Direwolf20-MC/MiningGadgets#96]
When you mine Sand in water with the Mining Gadget, it gets duped.Haven't tried Gravel yet but I guess it's related to gravity blocks. Still works using the latest 1.15.2 version of Mining Gadgets.

Edit : Gravel doesn't work?

**Comment by MichaelHillcox** [comment]
Can't reproduce. What upgrades did you have on the gadget?

**Comment by MichaelHillcox** [comment]
Please update this issue if you have found a way to reproduce this issue, thanks :+1:
