### ISSUE TITLE
[Idea] Pumping gadget

### ISSUE THREAD

**Issue by Venom31** [Direwolf20-MC/MiningGadgets#97]
As for the other mining gadgets, so that it's _gadgets_, in plural.

**Motivation**
One might say, mining gadget is used in mines and caves to get (mine) blocks out of the world. What if we extend the meaning of mining to get (pump) liquids out of the world? This may be useful for annoying water/lava/etc. blocking your way in a cave, or just for more convenient grabbing of liquid resource to fuel your contraptions (Tinkers' smeltery, oil processing, whatever). Ever since 1.7 mods, I haven't seen a tool similar to FluiVac from the old Thermal Expansion, and have been missing it quite a bit.

**Description**
A pumping gadget is a handheld tool that acts similarly to a mining gadget. Targeting liquid block (source or flowing - to be determined) and pressing and holding activation button (RMB click by default?), the gadget pumps said liquid out of the world. Since liquids aren't usually stored in item form, some tank is required for it to work. To determine which tank to transfer to, it can be held in the off-hand (in case there are multiple). If one doesn't care which tank to fill, holding any in the off-hand isn't mandatory. Holding one tank in the off-hand restricts operation to that one tank only.
One exception to the tank-in-inventory requirement might be made for Void Junk upgrade configured for voiding that specific liquid that player is pointing at.
Due to frequently irregular placement of liquid source blocks, and possibly large bodies of them, Size upgrades like 3x3 or 5x5 etc make less sense for pumping gadget. Maybe connected source blocks must be automatically pumped as well. A lot of questions arise with that in terms of performance and usability, so that too is to be determined.
Regarding the source-or-flowing question, that also has performance considerations to be made. If it's feasible, would be very nice to have flow-tracing capability, so that the caving player doesn't have to swim up just to block that one annoying water source block that cascaded all throughout a cave.
Another question is connection with storage medium(s). I wonder if it's possible to connect mining/pumping gadget with Refined Storage? That would be awesome!
Energy consumption may be assessed from the mentioned FluiVac from the old Thermal Expansion, it was using some RF per operation. Its operation was limited to one source block at a time though. By the way, the FluiVac had a reverse function - placing the liquids from tank back into the world. Maybe such function is also desirable, although the way it was done in Thermal FluiVac wasn't the best IMO. It was basically like emptying a bucket with respective liquid, with its fallacies of placing more than one into the same block space, potentially wasting valuable liquids. I wonder if that could be done better.

**Possible upgrades**
Void Junk - same as mining gadget, delete configured types of liquid without storing it.
Maximum Range - same as mining gadget, how far from the player tool is able to operate.
Lighting - same as mining gadget, lights up dark spots in the pumped out area.
Connected Sources - like size upgrades for mining gadget, but possibly ranging further out without player re-targeting - performance and usability issues are to be determined.
Trace Flow - regarding the source-or-flowing question, allows tracing back the flow to the very source block and pumping it out.
Landfill - fills the pumped out blocks back with configured item type. The items to do so must be in inventory. Placing blocks from landfill takes preference over the Lighting upgrade. The Landfill upgrade ties into the question of connection with storage medium(s). If it's feasible, the blocks to be used could be taken from the storage system.
Reverse Flow - allows switching to a mode that places source blocks in the world. One may use the off-hand with tank to specify which liquid to place. Again, usability questions are strong on this one. 

**Possible visuals**
Since laser wouldn't make much sense, a pipe of some kind may be shot in the direction of targeted block of liquid.

**Comment by MichaelHillcox** [comment]
This would need @Direwolf20-MC approval, but in basic terms for Dires time: He's effectively asking for another gadget like the mining gadget but instead it would suck up liquids but share a lot of traits from the mining gadget like range, etc. Some varied level storing that would need to be refined over time.

**Comment by Venom31** [comment]
Thank you for TL;DR version, @MichaelHillcox ! And there I was wondering what I missed all the time...
