### ISSUE TITLE
[1.15.2] Ticking Block Entity

### ISSUE THREAD

**Issue by NillerMedDild** [Direwolf20-MC/MiningGadgets#99]
My Enigmatica 5 server has crashed 3 times due to someone using a mining gadget. The crash doesn't happen immediately, usually after 30-60 seconds. 

I have not been able to reproduce it in singleplayer.

Previous versions of the modpack worked just fine, with the same version of Mining Gadgets, which leads me to believe it's a conflict with a newly added mod. The potential conflicting mods are:

- Immersive Engineering [\#345](https://github.com/NillerMedDild/Enigmatica5/issues/345)
- Dyeable Flower Pots [\#343](https://github.com/NillerMedDild/Enigmatica5/issues/343)
- Old Java Warning [\#152](https://github.com/NillerMedDild/Enigmatica5/issues/152)

It could also be an issue with newer Forge versions, as the previous modpack version used `1.15.2-31.2.9`

We will continue to search for the cause.

Crash report: https://gist.github.com/Darkere/8afa228057b4da64e87f228f34e196d7

### Versions
- mininggadgets-1.3.5
- Forge-1.15.2-31.2.20

Original issue: https://github.com/NillerMedDild/Enigmatica5/issues/363

Update: After breaking about 3000 blocks while mining on a server with the Mining Gadget, I have still not been able to reproduce this.

**Comment by MichaelHillcox** [comment]
Offending line

https://github.com/Direwolf20-MC/MiningGadgets/blob/master/src/main/java/com/direwolf20/mininggadgets/common/tiles/RenderBlockTileEntity.java#L272

I'm not sure what the other mods might be doing but I can likely resolve it just by fixing this if statement and making the entire class a little less fail prone. I'll see what is on this releases change long and see if it's enough to push out an update.

(Currently busy with work so within the next few days :+1:)

**Comment by NillerMedDild** [comment]
Oh awesome, thanks!

**Comment by NillerMedDild** [comment]
We haven't been able to reproduce this issue for quite some time, closing it for now :)
